### PR TITLE
Refactor: add consistent_read in example base on client_read API to provide consistent read from statemacine

### PR DESCRIPTION
**Pull request by lichuang**
1. Refactor: add consistent_read in example base on `is_leader` API to provide consistent read from statemacine"
2. rename API `client_read` to `is_leader`.
3. update gitignore file.

---
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/218)

### CODE REVIEW

**Review by drmingdrmer — APPROVED** [review]
LGTM:DDD

**Review by drmingdrmer — APPROVED** [review]
Looks good to me:DD

**Review by drmingdrmer — APPROVED** [review]
LGTM again:D

**Review by ariesdevil — APPROVED** [review]
LGTM

**Pull request merged**
