### PR TITLE
Feature: adding rkyv support

### PR DESCRIPTION
**Pull request by zach-schoenberger**
**Checklist**

- [x ] Updated guide with pertinent info (may not always apply). 
- [ x] Squash down commits to one or two logical commits which clearly describe the work you've done.
- [ ] Unittest is a friend:)

---
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/474)

### CODE REVIEW

**Review by drmingdrmer — COMMENTED** [review]
Thanks man!
The codes look neat and clean to me.
But how to test if this feature works as expected?

**Comment by zach-schoenberger** [comment]
Hey @drmingdrmer, thanks! I'm working on adding that now. Ideally also setting up a version of the cluster benchmark referenced in the Readme.

**Comment by zach-schoenberger** [comment]
I'm going to close this PR for the moment while I add more to it. I don't want to keep generating unnecessary events.

**Comment by zach-schoenberger** [comment]
@drmingdrmer So after digging through setting up tests, I've come to the conclusion that adding this support doesn't really make sense IMO. At a high level it sounds like a good idea. But when it comes to the implementation it breaks down. rkyv is a great library, and I've used it in other projects. But it introduces a model that doesn't work well with the current raft API in this project. rkyv introduces the concept of an Archive data type, which is the serialized version of the data type that the annotations are applied to. The archive is typically what is used to access fields so that way deserialization is not needed (hence the zero copy). In order to get the advantage of the Archive concept, openraft would have to accept the archive as apart of the api layer, like here: https://github.com/datafuselabs/openraft/blob/1202d1b059f7e07f0f3353b74f0b2795f063ab56/openraft/src/raft.rs#L218-L221

It's pretty straight forward to just add the macros to allow for creating the rkyv Archives to the data types in openraft, but it won't actually give the benefit unless the raft api allows for them to be used. Because right now you would still have to deserialize the Archive sent across the wire to use the API. 

A pretty straight forward work around without any API changes is to just use the Archive (aka Vec<u8>) in the AppData/AppResponseData so that way the deserialization will be much faster than if it were a complex Struct/Enum.

I can still finish out the PR if this is still wanted, just not sure if it makes sense to now.

**Comment by drmingdrmer** [comment]
It's a closed PR thus I've redirected the discussion to a new issue:
https://github.com/datafuselabs/openraft/issues/479

**Pull request closed without merging**
