### PR TITLE
Refactor: gate tokio rt with feature tokio-rt

### PR DESCRIPTION
**Pull request by SteveLauC**
### What does this PR do

Gates the tokio runtime with a new feature `tokio-rt`, and makes it a default feature.

1. Replaces `tokio_select!()` with `futures::select_biased!()`
2.  Everything related to Tokio is now hidden behind the `tokio-rt` feature.

### About the `declare_raft_types!` macro

I haven't done anything to this because I haven't found a good way to update it, currently, with the `default` (`tokio-rt`) feature off, using this macro without providing a runtime would result in a compile error:

```sh
error[E0412]: cannot find type `TokioRuntime` in module `$crate::impls`
 --> src/main.rs:3:1
  |
3 | declare_raft_types!(pub TypeConfig);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `$crate::impls`
  |
note: found an item that was configured out
 --> /home/steve/Documents/workspace/INFINI/openraft/openraft/src/impls/mod.rs:8:51
  |
8 | pub use crate::type_config::async_runtime::impls::TokioRuntime;
  |                                                   ^^^^^^^^^^^^
  = note: the item is gated behind the `tokio-rt` feature
  = note: this error originates in the macro `$crate::declare_raft_types` which comes from the expansion of the macro `declare_raft_types` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Checklist**

- [ ] Updated guide with pertinent info (may not always apply). 
- [x] Squash down commits to one or two logical commits which clearly describe the work you've done.
- [ ] Unittest is a friend:)

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)

### CODE REVIEW

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: 0 of 15 files reviewed, 1 unresolved discussion

___
*[`openraft/src/raft/mod.rs` line 171 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2sfH3g4DAyXNi7PKF4:-O2sfH3g4DAyXNi7PKF5:b-dd9rdn) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/raft/mod.rs#L171)):*
> ```XML
>                 (Node         , , $crate::impls::BasicNode              ),
>                 (Entry        , , $crate::impls::Entry<Self>            ),
>                 (SnapshotData , , std::io::Cursor<Vec<u8>>                       ),
> ```

Use the full path here so that users won't need to manually import it when using this default value.

**Review by schreter — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: all files reviewed, 3 unresolved discussions (waiting on @SteveLauC)

___
*[`openraft/src/metrics/wait.rs` line 69 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2tuiu08qVppox6lL6Y:-O2tuiu08qVppox6lL6Z:b-njb9pv) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/metrics/wait.rs#L69)):*
> ```XML
>             futures::select_biased! {
>                 _ = delay.fuse() => {
>                 tracing::debug!( "id={} timeout wait {:} latest: {}", latest.id, msg.to_string(), latest );
> ```

You might want to correct indentation here.
___
*[`openraft/src/network/snapshot_transport.rs` line 5 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2tupyh8D2F5bXA-jgD:-O2tupyh8D2F5bXA-jgE:b-g1ijfn) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/network/snapshot_transport.rs#L5)):*
> ```XML
> 
> use std::future::Future;
> #[cfg(feature = "tokio-rt")]
> ```

Instead of many markers, you could group all relevant imports in a private `mod tokio_deps` or so and then `use tokio_imports::*`, so you'll only need two `cfg` markers.

Similarly, the `tokio_deps` module could also contain relevant `impl`s from below, since they can be anywhere in the crate.
___
*[`openraft/src/raft/mod.rs` line 33 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2tvQzr7umM-tuOS8Ek:-O2tvQzr7umM-tuOS8El:b-4a3h5q) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/raft/mod.rs#L33)):*
> ```XML
> use std::time::Duration;
> 
> use async_lock::Mutex;
> ```

I'd suggest to move this to the `AsyncRuntime`, alongside other sync primitives we already have there.

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @drmingdrmer and @schreter)

___
*[`openraft/src/metrics/wait.rs` line 69 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2tuiu08qVppox6lL6Y:-O2w4_GEDmXXbHJcrcSr:byqz8jv) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/metrics/wait.rs#L69)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

You might want to correct indentation here.
</blockquote></details>

Thanks for catching it! Done:)
___
*[`openraft/src/network/snapshot_transport.rs` line 5 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2tupyh8D2F5bXA-jgD:-O2wAQ6U8uactD3lVtrj:b4wol6m) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/network/snapshot_transport.rs#L5)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Instead of many markers, you could group all relevant imports in a private `mod tokio_deps` or so and then `use tokio_imports::*`, so you'll only need two `cfg` markers.

Similarly, the `tokio_deps` module could also contain relevant `impl`s from below, since they can be anywhere in the crate.
</blockquote></details>

It seems that if we move the implementation to this private module, then we don't need to `use tokio_imports::*` as the things that need tokio are already in the module.

Done.
___
*[`openraft/src/raft/mod.rs` line 33 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2tvQzr7umM-tuOS8Ek:-O2wByPd6sLQhN8KasTX:b-r3o5o0) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/raft/mod.rs#L33)):*
Emm, previously @drmingdrmer said:

> It's alright to mock a `Mutex` instead of requiring user to implement it.


Perhaps we could discuss a bit before adding it:)

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 10 of 15 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: 14 of 15 files reviewed, 5 unresolved discussions (waiting on @schreter and @SteveLauC)

___
*[`openraft/src/engine/log_id_list.rs` line 305 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2wXduG7yvjQuk0cnz4:-O2wXduG7yvjQuk0cnz5:b-b2b2lw) ([raw file](https://github.com/datafuselabs/openraft/blob/d6e0c3fea56974c6e4dea57253febb48d085a7f8/openraft/src/engine/log_id_list.rs#L305)):*
> ```XML
>     pub(crate) fn key_log_ids(&self) -> &[LogId<C::NodeId>] {
>         &self.key_log_ids
>     }
> ```

Why does this method requires `tokio-rs`?



_Code quote:_
```XML
    #[cfg(feature = "tokio-rt")]
    pub(crate) fn key_log_ids(&self) -> &[LogId<C::NodeId>] {
        &self.key_log_ids
    }
```
___
*[`openraft/src/raft/mod.rs` line 33 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2tvQzr7umM-tuOS8Ek:-O2wY2tf1O_UbSAqKWzH:b-816h2o) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/raft/mod.rs#L33)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

Emm, previously @drmingdrmer said:

> It's alright to mock a `Mutex` instead of requiring user to implement it.


Perhaps we could discuss a bit before adding it:)
</blockquote></details>

Let's discuss here:
- https://github.com/datafuselabs/openraft/pull/1208
___
*[`openraft/src/raft/mod.rs` line 171 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2sfH3g4DAyXNi7PKF4:-O2wYAVREEEIMikzc4Vo:btojbfd) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/raft/mod.rs#L171)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

Use the full path here so that users won't need to manually import it when using this default value.
</blockquote></details>

Great!
___
*[`openraft/src/type_config/async_runtime/mod.rs` line 12 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2wYXM-D-nVPeJbnaCF:-O2wYXM0BMzyEibrEpAd:bq571bu) ([raw file](https://github.com/datafuselabs/openraft/blob/d6e0c3fea56974c6e4dea57253febb48d085a7f8/openraft/src/type_config/async_runtime/mod.rs#L12)):*
> ```XML
>     #[cfg(feature = "tokio-rt")]
>     pub use tokio_runtime::TokioRuntime;
> }
> ```

The `impls` module is specifically designed for use with Tokio. It would be more appropriately named `tokio_impls`. Additionally, the relevant attribute should be applied to this module to clarify its purpose.



_Code quote:_
```XML
pub(crate) mod impls {
    #[cfg(feature = "tokio-rt")]
    mod tokio_runtime;

    #[cfg(feature = "tokio-rt")]
    pub use tokio_runtime::TokioRuntime;
}
```

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @drmingdrmer and @schreter)

___
*[`openraft/src/engine/log_id_list.rs` line 305 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2wXduG7yvjQuk0cnz4:-O2wrhX_5ytMSHZSU6Bx:b-4gr63u) ([raw file](https://github.com/datafuselabs/openraft/blob/d6e0c3fea56974c6e4dea57253febb48d085a7f8/openraft/src/engine/log_id_list.rs#L305)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Why does this method requires `tokio-rs`?
</blockquote></details>

Sorry for being unclear, the attribute should be:

```rs
    #[cfg_attr(not(feature = "tokio-rt"), allow(dead_code))]
```

as this method will only be used under feature tokio-rt.
___
*[`openraft/src/type_config/async_runtime/mod.rs` line 12 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2wYXM-D-nVPeJbnaCF:-O2wsh887XWJSy4-1UVy:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/d6e0c3fea56974c6e4dea57253febb48d085a7f8/openraft/src/type_config/async_runtime/mod.rs#L12)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

The `impls` module is specifically designed for use with Tokio. It would be more appropriately named `tokio_impls`. Additionally, the relevant attribute should be applied to this module to clarify its purpose.
</blockquote></details>

Done.

**Review by schreter — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: all files reviewed, 2 unresolved discussions (waiting on @drmingdrmer and @SteveLauC)

___
*[`openraft/src/engine/log_id_list.rs` line 305 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2wXduG7yvjQuk0cnz4:-O2x_ClaCXHLFXWg2eCF:b1n2xc6) ([raw file](https://github.com/datafuselabs/openraft/blob/d6e0c3fea56974c6e4dea57253febb48d085a7f8/openraft/src/engine/log_id_list.rs#L305)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

Sorry for being unclear, the attribute should be:

```rs
    #[cfg_attr(not(feature = "tokio-rt"), allow(dead_code))]
```

as this method will only be used under feature tokio-rt.
</blockquote></details>

I think it would make sense to make this method simply `pub`, since it's used in many tests. Tests with other runtimes might want to request the log IDs as well.
___
*[`openraft/src/network/snapshot_transport.rs` line 5 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2tupyh8D2F5bXA-jgD:-O2x_Tvg17lMytLu0QM_:b-7rcrgu) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/network/snapshot_transport.rs#L5)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

It seems that if we move the implementation to this private module, then we don't need to `use tokio_imports::*` as the things that need tokio are already in the module.

Done.
</blockquote></details>

I didn't check the large move, but I assume it's just a move. If not, please mark code needing extra review.

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: all files reviewed, 2 unresolved discussions (waiting on @drmingdrmer and @schreter)

___
*[`openraft/src/engine/log_id_list.rs` line 305 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2wXduG7yvjQuk0cnz4:-O2xbsx8EY3c1HpzjVcb:baxozm2) ([raw file](https://github.com/datafuselabs/openraft/blob/d6e0c3fea56974c6e4dea57253febb48d085a7f8/openraft/src/engine/log_id_list.rs#L305)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

I think it would make sense to make this method simply `pub`, since it's used in many tests. Tests with other runtimes might want to request the log IDs as well.
</blockquote></details>

I think we can do this in the future when the support for other runtimes is added as we are currently [not sure how to test a new async runtime](https://github.com/datafuselabs/openraft/issues/1209)
___
*[`openraft/src/network/snapshot_transport.rs` line 5 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2tupyh8D2F5bXA-jgD:-O2xcV4v0GDSa3X0WmxV:b-3ag1q7) ([raw file](https://github.com/datafuselabs/openraft/blob/91b8a0a83b4a966ca4c577ac0ac7c14b0edb4894/openraft/src/network/snapshot_transport.rs#L5)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

I didn't check the large move, but I assume it's just a move. If not, please mark code needing extra review.
</blockquote></details>

It is just a move, please see this [commit](https://github.com/datafuselabs/openraft/pull/1207/commits/d6e0c3fea56974c6e4dea57253febb48d085a7f8).

**Review by schreter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: all files reviewed, 1 unresolved discussion (waiting on @drmingdrmer)

___
*[`openraft/src/engine/log_id_list.rs` line 305 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2wXduG7yvjQuk0cnz4:-O2yFJRW70c_H_eDkLDJ:bkgn1f3) ([raw file](https://github.com/datafuselabs/openraft/blob/d6e0c3fea56974c6e4dea57253febb48d085a7f8/openraft/src/engine/log_id_list.rs#L305)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

I think we can do this in the future when the support for other runtimes is added as we are currently [not sure how to test a new async runtime](https://github.com/datafuselabs/openraft/issues/1209)
</blockquote></details>

Of course, you can keep it as-is. Just most likely it will be needed sooner or later. But, not sure.

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: all files reviewed, 2 unresolved discussions (waiting on @SteveLauC)

___
*[`openraft/src/raft/mod.rs` line 46 at r4](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O3A_9IcA9QktmPU_vHJ:-O3A_9IcA9QktmPU_vHK:b-7pxv8j) ([raw file](https://github.com/datafuselabs/openraft/blob/6368d5f52874ce03fb61dd8d065080daa7aa9158/openraft/src/raft/mod.rs#L46)):*
> ```XML
> 
> #[cfg(feature = "tokio-rt")]
> use crate::async_runtime::mutex::Mutex;
> ```

Mutex is defined by async-runtime thus it does no need `tokio-rs` feature enabled. no?



_Code quote:_
```XML
#[cfg(feature = "tokio-rt")]
use crate::async_runtime::mutex::Mutex;
```

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: all files reviewed, 2 unresolved discussions (waiting on @drmingdrmer)

___
*[`openraft/src/engine/log_id_list.rs` line 305 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O2wXduG7yvjQuk0cnz4:-O3AaK438pvfws94NNgx:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/d6e0c3fea56974c6e4dea57253febb48d085a7f8/openraft/src/engine/log_id_list.rs#L305)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Of course, you can keep it as-is. Just most likely it will be needed sooner or later. But, not sure.
</blockquote></details>

Done.
___
*[`openraft/src/raft/mod.rs` line 46 at r4](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O3A_9IcA9QktmPU_vHJ:-O3AaKkp3zD_NK-k5pu2:b1qnvak) ([raw file](https://github.com/datafuselabs/openraft/blob/6368d5f52874ce03fb61dd8d065080daa7aa9158/openraft/src/raft/mod.rs#L46)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Mutex is defined by async-runtime thus it does no need `tokio-rs` feature enabled. no?
</blockquote></details>

It is currently only used under the feature `tokio-rt`, do I need to change it to:

```
#[cfg_attr(not(feature = "tokio-rt"), allow(unused_imports))]
```

to make it more clear?

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: all files reviewed, 2 unresolved discussions (waiting on @SteveLauC)

___
*[`openraft/src/raft/mod.rs` line 46 at r4](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O3A_9IcA9QktmPU_vHJ:-O3AbkgP9rgxPcvAGNSw:b8fnwo4) ([raw file](https://github.com/datafuselabs/openraft/blob/6368d5f52874ce03fb61dd8d065080daa7aa9158/openraft/src/raft/mod.rs#L46)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

It is currently only used under the feature `tokio-rt`, do I need to change it to:

```
#[cfg_attr(not(feature = "tokio-rt"), allow(unused_imports))]
```

to make it more clear?
</blockquote></details>

If it is not required by this file but only by a function,
you can just move this `use` to the function `install_snapshot`.

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @drmingdrmer)

___
*[`openraft/src/raft/mod.rs` line 46 at r4](https://reviewable.io/reviews/datafuselabs/openraft/1207#-O3A_9IcA9QktmPU_vHJ:-O3AdWnc29JhvJVVKW2W:bmxun5x) ([raw file](https://github.com/datafuselabs/openraft/blob/6368d5f52874ce03fb61dd8d065080daa7aa9158/openraft/src/raft/mod.rs#L46)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

If it is not required by this file but only by a function,
you can just move this `use` to the function `install_snapshot`.
</blockquote></details>

That's a style I really love, extremely helpful when you are in a big bowl of `cfg` soup, done!

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SteveLauC)

**Comment by SteveLauC** [comment]
Let me squash the commits:)

**Comment by SteveLauC** [comment]
Commits squashed

**Comment by SteveLauC** [comment]
Well, I cannot reproduce that [test failure](https://github.com/datafuselabs/openraft/actions/runs/10207624483/job/28242736726?pr=1207) locally:>

**Comment by drmingdrmer** [comment]
> Well, I cannot reproduce that [test failure](https://github.com/datafuselabs/openraft/actions/runs/10207624483/job/28242736726?pr=1207) locally:>

These tests are run with `OPENRAFT_NETWORK_SEND_DELAY` set to 30 milliseconds to simulate network delay.
Did you run it locally with this environment variable set?
`OPENRAFT_NETWORK_SEND_DELAY=30 cargo test`

I'll have a look on the logs to see what's going wrong:
The log can be found in the artifacts archive: https://github.com/datafuselabs/openraft/actions/runs/10207624483?pr=1207#artifacts

**Comment by SteveLauC** [comment]
Thanks for showing me that parameter!

I just tried 17 times with that option, but I didn't reproduce the failure that occurred in CI, instead, I got this one:

```sh
failures:
    t11_add_learner::check_learner_after_leader_transferred

test result: FAILED. 39 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 13.68sj
```

Though this test's log was mixed with previous tests' log so I cannot provide it :disappointed:

**Comment by drmingdrmer** [comment]
> Thanks for showing me that parameter!
> 
> I just tried 17 times with that option, but I didn't reproduce the failure that occurred in CI, instead, I got this one:
> 
> ```shell
> failures:
>     t11_add_learner::check_learner_after_leader_transferred
> 
> test result: FAILED. 39 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 13.68sj
> ```
> 
> Though this test's log was mixed with previous tests' log so I cannot provide it 😞

It appears that these failures are not related to this PR. I will investigate to determine the cause.

**Comment by drmingdrmer** [comment]
The failure should be fixed in:
- #1220

**Comment by drmingdrmer** [comment]
> The failure should be fixed in:
> 
> * [Fix: (0.10) Clarify that receiving an equal vote does not grant leadership. #1220](https://github.com/datafuselabs/openraft/pull/1220)

Merged and there should not be such issue any more 🤔

**Comment by SteveLauC** [comment]
Rebased.

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1207)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SteveLauC)

**Pull request merged**
