### PR TITLE
Doc: add License link

### PR DESCRIPTION
**Pull request by caicancai**
**Checklist**

- [ ] Updated guide with pertinent info (may not always apply). 
- [ ] Squash down commits to one or two logical commits which clearly describe the work you've done.
- [ ] Unittest is a friend:)

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/932)

### CODE REVIEW

**Comment by caicancai** [comment]
@drmingdrmer Hi, I found that my previous mention in the main branch seemed a little unreasonable, so I re-mentioned a pr, for which I am sorry

**Comment by drmingdrmer** [comment]
It has come to my attention that the README file is also utilized on docs.rs. Therefore, using local links could lead to broken links on the docs.rs platform.

**Comment by caicancai** [comment]
> It has come to my attention that the README file is also utilized on docs.rs. Therefore, using local links could lead to broken links on the docs.rs platform.

Thanks for reminding me. I'll change the official link

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/932)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @caicancai)

**Comment by caicancai** [comment]
I seem to have typed one space less, and I'm sorry for that

**Pull request merged**
