### PR TITLE
Refactor: add QuorumSet::ids() to return all ids

### PR DESCRIPTION
**Pull request by drmingdrmer**
##### Refactor: add QuorumSet::ids() to return all ids

---
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/405)

### CODE REVIEW

**Review by schreter — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/405)* status: all files reviewed, 5 unresolved discussions

___
*[`openraft/src/membership/membership.rs` line 366 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9_YkE0zq4hHGUhbo:-N5U9_YlCGuMs5nECvaX:bbxxqqd) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/membership/membership.rs#L366)):*
> ```XML
>     }
> 
>     fn ids(&self) -> BTreeSet<NID> {
> ```

Why not a simple `Iterator` over NIDs (associated type)?
___
*[`openraft/src/quorum/joint.rs` line 57 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9fcl8ulsuzyHD7SX:-N5U9fcl8ulsuzyHD7SY:b5nlml5) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/joint.rs#L57)):*
> ```XML
>     }
> 
>     fn ids(&self) -> BTreeSet<ID> {
> ```

In this, you can still build `BTreeSet` internally and then convert it into iterator (see `IntoIterator` trait implemented for`BTreeSet`).

The implementation is still suboptimal, since it allocates just to provide the iteration over IDs. For joint consensus of 2 (which is IIRC the use case), it would be in fact much more efficient to write a custom iterator as a composition of first iterating the first child IDs and then iterating second child IDs filtered by first child IDs. This could be generalized for multiple levels as well, of course, always checking all previous levels first to filter out IDs which have been delivered.

Due to the quadratic complexity, this will of course work well only for typical cases of 1 or 2 levels in the joint consensus and typical 3-7 quorum sizes. With 1-2 levels, the performance break-even with allocation and BTreeSet will be IMHO somewhere at ~30-50 participants (just a gut feeling).
___
*[`openraft/src/quorum/joint.rs` line 67 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UA4YREaISEKV2O8Ch:-N5UA4YREaISEKV2O8Ci:bxdwsr7) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/joint.rs#L67)):*
> ```XML
> 
> /// Implement QuorumSet for Joint<..Vec<QS>>
> impl<ID, QS> QuorumSet<ID> for Joint<ID, QS, Vec<QS>>
> ```

Why the second implementation? Both `Vec` and `&[]` provide `AsRef` trait, which converts them to `&[]`. You can simply require that the third parameter implements `AsRef<[ID]>` and implement it generically.
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 24 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UCb5S2rgBsBiAdMu3:-N5UCb5S2rgBsBiAdMu4:b-9juzq9) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/quorum_set_impl.rs#L24)):*
> ```XML
> 
>     fn ids(&self) -> BTreeSet<ID> {
>         self.iter().copied().collect::<BTreeSet<_>>()
> ```

You could simply `clone()` the `BTreeSet`. But, in fact, if you rework this with `Iterator`, then `self.iter()` will be obviously most efficient.
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 46 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UD5zL3d-KJkno_ENq:-N5UD5zL3d-KJkno_ENr:bie2lil) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/quorum_set_impl.rs#L46)):*
> ```XML
>     }
> 
>     fn ids(&self) -> BTreeSet<ID> {
> ```

In fact, why define `ids()` in the first place? You could simply require that `QuorumSet` trait implements an `Iterator` over node IDs (as a supertrait). That way, you just need to implement it for joint consensus.

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/405)* status: all files reviewed, 5 unresolved discussions

___
*[`openraft/src/membership/membership.rs` line 366 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9_YkE0zq4hHGUhbo:-N5Up2324S1IkrwEKelo:bd93hqw) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/membership/membership.rs#L366)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Why not a simple `Iterator` over NIDs (associated type)?
</blockquote></details>

Because the `ids` should be deduplicated before returning it:(
___
*[`openraft/src/quorum/joint.rs` line 57 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9fcl8ulsuzyHD7SX:-N5Uq_qQCCzPAk_XTzW_:b-fs6loh) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/joint.rs#L57)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

In this, you can still build `BTreeSet` internally and then convert it into iterator (see `IntoIterator` trait implemented for`BTreeSet`).

The implementation is still suboptimal, since it allocates just to provide the iteration over IDs. For joint consensus of 2 (which is IIRC the use case), it would be in fact much more efficient to write a custom iterator as a composition of first iterating the first child IDs and then iterating second child IDs filtered by first child IDs. This could be generalized for multiple levels as well, of course, always checking all previous levels first to filter out IDs which have been delivered.

Due to the quadratic complexity, this will of course work well only for typical cases of 1 or 2 levels in the joint consensus and typical 3-7 quorum sizes. With 1-2 levels, the performance break-even with allocation and BTreeSet will be IMHO somewhere at ~30-50 participants (just a gut feeling).
</blockquote></details>

Getting `ids` won't be frequently used. It only happens when there is a `Membership` log entry and openraft needs to rebuild a `QuorumSet` and to update the `Progress`.
Thus I tried to keep simplicity over performance on this part.:)
___
*[`openraft/src/quorum/joint.rs` line 67 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UA4YREaISEKV2O8Ch:-N5Uat1G20769X2tb3Ff:btwou5x) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/joint.rs#L67)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Why the second implementation? Both `Vec` and `&[]` provide `AsRef` trait, which converts them to `&[]`. You can simply require that the third parameter implements `AsRef<[ID]>` and implement it generically.
</blockquote></details>

I tried to find a way to provide a universal generic type for both of them and was not aware of `AsRef`.
Thank you my hero!:DD
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 24 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UCb5S2rgBsBiAdMu3:-N5UbGDt2Os03Qlq8lWA:b-29mqm3) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/quorum_set_impl.rs#L24)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

You could simply `clone()` the `BTreeSet`. But, in fact, if you rework this with `Iterator`, then `self.iter()` will be obviously most efficient.
</blockquote></details>

The returned `ids` should be de-duplicated.
And for joint config IMHO there is no way to dedup `id` in the returned iterator without a map like temporary container. Thus I decide to return just a btreeset.
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 46 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UD5zL3d-KJkno_ENq:-N5UoY569q_-MklWdNSd:bffmvs8) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/quorum_set_impl.rs#L46)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

In fact, why define `ids()` in the first place? You could simply require that `QuorumSet` trait implements an `Iterator` over node IDs (as a supertrait). That way, you just need to implement it for joint consensus.
</blockquote></details>

For the same reason, the returned `ids` should be deduplicated.

And fetching the `ids` is only used when building a `Progress`, it is not in the hot path. Hoping it won't be an issue:D

**Review by schreter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/405)* status: all files reviewed, 5 unresolved discussions

___
*[`openraft/src/membership/membership.rs` line 366 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9_YkE0zq4hHGUhbo:-N5UwwFi0uEB-RoSgvJh:bcg3d2r) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/membership/membership.rs#L366)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Because the `ids` should be deduplicated before returning it:(
</blockquote></details>

Sure, but that has nothing to do with return type being an iterator. You can "convert" a `BTreeSet` into an `Iterator` via `IntoIterator` trait, which is implemented for it. So temporarily you'd build the `BTreeSet` and then convert it into iterator, which hides the implementation details.

I'm maybe a bit too picky, since we have certain code quality standards in our project where we want to use openraft :-) and that's why I'm commenting on interfaces so much (when time permits).
___
*[`openraft/src/quorum/joint.rs` line 57 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9fcl8ulsuzyHD7SX:-N5Ux-fo2fsZAEl1v2Cq:b-o2f5vv) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/joint.rs#L57)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Getting `ids` won't be frequently used. It only happens when there is a `Membership` log entry and openraft needs to rebuild a `QuorumSet` and to update the `Progress`.
Thus I tried to keep simplicity over performance on this part.:)


</blockquote></details>

That's OK and understandable. Nevertheless, using explicit `BTreeSet` instead of iterator will limit potential future optimizations. As noted above, you can convert the `BTreeSet` to an `Iterator` easily and return it, so the caller doesn't know it's a `BTreeSet`, he just knows what to expect to get from the iterator.
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 24 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UCb5S2rgBsBiAdMu3:-N5UxLsY9KZAamC4NF1t:b-r84djs) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/quorum_set_impl.rs#L24)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

The returned `ids` should be de-duplicated.
And for joint config IMHO there is no way to dedup `id` in the returned iterator without a map like temporary container. Thus I decide to return just a btreeset.


</blockquote></details>

Independent of the return type change, this implementation is basically a `clone()`. So simply calling `self.clone()` will return what you want, since IDs are not duplicated in `BTreeSet`.
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 46 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UD5zL3d-KJkno_ENq:-N5UxcVO3p4ZooCxBTXo:bx9hr4) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/quorum_set_impl.rs#L46)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

For the same reason, the returned `ids` should be deduplicated.

And fetching the `ids` is only used when building a `Progress`, it is not in the hot path. Hoping it won't be an issue:D
</blockquote></details>

Sure, it won't be a performance issue.

But, also here, we are expecting the vector to contain unique IDs in a QuorumSet, don't we?

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/405)* status: all files reviewed, 2 unresolved discussions

___
*[`openraft/src/membership/membership.rs` line 366 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9_YkE0zq4hHGUhbo:-N5V3q-mALbeloJfy8Et:b95lund) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/membership/membership.rs#L366)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Sure, but that has nothing to do with return type being an iterator. You can "convert" a `BTreeSet` into an `Iterator` via `IntoIterator` trait, which is implemented for it. So temporarily you'd build the `BTreeSet` and then convert it into iterator, which hides the implementation details.

I'm maybe a bit too picky, since we have certain code quality standards in our project where we want to use openraft :-) and that's why I'm commenting on interfaces so much (when time permits).
</blockquote></details>

Make sense:D.

You've given pretty good advice. I'd appreciate it.

But, in order to use an `Iterator` as the return value type in a trait, it seems to have to introduce an associated type to the trait.

```rust
trait Q {
   fn foo() -> impl Iterator<Item=()>; // this just won't compile
}
```

```rust
trait Q {
  fn foo<T: Iterator<Item=()>>() -> T;
}
impl Q for Foo {
  fn foo<T: Iterator<Item=()>>() -> T { btreeset!{}.into_iter() } // The compiler complains about different type 
}
```

```test
13 |     fn foo<T:Iterator<Item=()>>() -> T{
   |            - this type parameter     - expected `T` because of return type
14 |         BTreeSet::new().into_iter()
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected type parameter `T`, found struct `std::collections::btree_set::IntoIter`
```

The only way is to introduce a type, will this be a little inconvenient to you?

```rust
trait Q<ID> {
    type T: Iterator<Item=ID>;
    fn foo() -> Self::T;
}

struct Foo {}

impl Q<u32> for Foo {
    type T = std::collections::btree_set::IntoIter<u32>;
    fn foo() -> Self::T{ BTreeSet::new().into_iter() }
}

```
___
*[`openraft/src/quorum/joint.rs` line 57 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9fcl8ulsuzyHD7SX:-N5V1Uqi01HWYIxd2PoI:b-3a150h) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/joint.rs#L57)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

That's OK and understandable. Nevertheless, using explicit `BTreeSet` instead of iterator will limit potential future optimizations. As noted above, you can convert the `BTreeSet` to an `Iterator` easily and return it, so the caller doesn't know it's a `BTreeSet`, he just knows what to expect to get from the iterator.
</blockquote></details>

You convinced me:D
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 24 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UCb5S2rgBsBiAdMu3:-N5V1i0-2A5d19-LyfPw:bbw4m86) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/quorum_set_impl.rs#L24)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Independent of the return type change, this implementation is basically a `clone()`. So simply calling `self.clone()` will return what you want, since IDs are not duplicated in `BTreeSet`.
</blockquote></details>

Right:)
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 46 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UD5zL3d-KJkno_ENq:-N5V1vVY9H_iYw50Keyo:bd235jk) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/quorum_set_impl.rs#L46)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Sure, it won't be a performance issue.

But, also here, we are expecting the vector to contain unique IDs in a QuorumSet, don't we?
</blockquote></details>

Make sense:)

**Review by schreter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/405)* status: all files reviewed, 2 unresolved discussions

___
*[`openraft/src/membership/membership.rs` line 366 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9_YkE0zq4hHGUhbo:-N5VRa0p7kTpfKJ164YA:bgwp8zt) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/membership/membership.rs#L366)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Make sense:D.

You've given pretty good advice. I'd appreciate it.

But, in order to use an `Iterator` as the return value type in a trait, it seems to have to introduce an associated type to the trait.

```rust
trait Q {
   fn foo() -> impl Iterator<Item=()>; // this just won't compile
}
```

```rust
trait Q {
  fn foo<T: Iterator<Item=()>>() -> T;
}
impl Q for Foo {
  fn foo<T: Iterator<Item=()>>() -> T { btreeset!{}.into_iter() } // The compiler complains about different type 
}
```

```test
13 |     fn foo<T:Iterator<Item=()>>() -> T{
   |            - this type parameter     - expected `T` because of return type
14 |         BTreeSet::new().into_iter()
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected type parameter `T`, found struct `std::collections::btree_set::IntoIter`
```

The only way is to introduce a type, will this be a little inconvenient to you?

```rust
trait Q<ID> {
    type T: Iterator<Item=ID>;
    fn foo() -> Self::T;
}

struct Foo {}

impl Q<u32> for Foo {
    type T = std::collections::btree_set::IntoIter<u32>;
    fn foo() -> Self::T{ BTreeSet::new().into_iter() }
}

```
</blockquote></details>

That's correct, you have to define the iterator as an associated type if you want to make it generic. That's why I wrote `Self::IdIterator` in the example.

However, due to lack of GATs and type alias impl traits in stable (I hope it'll get stable soon, it's way too valuable), you need to do some tricks to return iterators. See for example the article https://depth-first.com/articles/2020/06/22/returning-rust-iterators/ which shows options (especially the last complex delegation) how to work around the limitations.

Thinking about it, the easiest way here for now would be either to return a fixed type (like the `BTreeSet` iterator for now) or an enum which has the "right" iterator inside of it (`BTreeSet` or `slice`) and delegates appropriately. Probably the former to get it off the ground, it can be improved later. Doing complex delegation is like cracking the nut with the sledgehammer (and GATs/type alias impl traits will solve this issue ultimately).
___
*[`openraft/src/quorum/joint.rs` line 67 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UA4YREaISEKV2O8Ch:-N5VbluK64ji_rIsNLCZ:b-e6ytq9) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/joint.rs#L67)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

I tried to find a way to provide a universal generic type for both of them and was not aware of `AsRef`.
Thank you my hero!:DD
</blockquote></details>

Yeah, for that, you need min_specialization, which didn't land in stable yet. Again, I hope it'll land soon, since it's quite valuable for such use cases.

**Review by schreter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/405)* status: all files reviewed, 2 unresolved discussions

___
*[`openraft/src/membership/membership.rs` line 366 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9_YkE0zq4hHGUhbo:-N5VcW9XBNb8tXik7hIi:btjwhop) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/membership/membership.rs#L366)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

That's correct, you have to define the iterator as an associated type if you want to make it generic. That's why I wrote `Self::IdIterator` in the example.

However, due to lack of GATs and type alias impl traits in stable (I hope it'll get stable soon, it's way too valuable), you need to do some tricks to return iterators. See for example the article https://depth-first.com/articles/2020/06/22/returning-rust-iterators/ which shows options (especially the last complex delegation) how to work around the limitations.

Thinking about it, the easiest way here for now would be either to return a fixed type (like the `BTreeSet` iterator for now) or an enum which has the "right" iterator inside of it (`BTreeSet` or `slice`) and delegates appropriately. Probably the former to get it off the ground, it can be improved later. Doing complex delegation is like cracking the nut with the sledgehammer (and GATs/type alias impl traits will solve this issue ultimately).
</blockquote></details>

Ah sorry, to clear the confusion, the complex delegation in the article above doesn't show it for the traits. But, the article shows the relatively simple possibility how to do it for traits, at the expense of adding a lifetime marker to the trait (and the impl can implement it via HRTBs with `for <'a>` syntax).

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/405)* status: all files reviewed, 1 unresolved discussion

___
*[`openraft/src/membership/membership.rs` line 366 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9_YkE0zq4hHGUhbo:-N5Yg-SO-EncRrm3Kl0s:bsmgii3) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/membership/membership.rs#L366)):*
Looks like `btree_set::IntoIter` is a simple enough solution for now:DDD

> That's why I wrote Self::IdIterator in the example.

It does not matter at all but where is `Self::IdIterator` and the example you wrote? Did I miss something? :thinking: 
___
*[`openraft/src/quorum/joint.rs` line 67 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5UA4YREaISEKV2O8Ch:-N5Yt7rnDJ1j9MhLSG7_:b2nh52p) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/quorum/joint.rs#L67)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Yeah, for that, you need min_specialization, which didn't land in stable yet. Again, I hope it'll land soon, since it's quite valuable for such use cases.
</blockquote></details>

:D

**Review by schreter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/405)* status: all files reviewed, 1 unresolved discussion

___
*[`openraft/src/membership/membership.rs` line 366 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9_YkE0zq4hHGUhbo:-N5Z0saK2sGyPurd0LDR:b2xpnd8) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/membership/membership.rs#L366)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Looks like `btree_set::IntoIter` is a simple enough solution for now:DDD

> That's why I wrote Self::IdIterator in the example.

It does not matter at all but where is `Self::IdIterator` and the example you wrote? Did I miss something? :thinking: 

</blockquote></details>

I did not put in the whole example, the `Self::IdIterator` was meant as an exercise to the reader :-). I.e., it's well-known that returning `impl Trait` is not allowed in trait methods, so I assumed, you'd automatically understand it as an associated type.

Well, I'm probably doing too much "hacky" Rust :-). We actually enabled some of the close-to-finalization features to ease development, so we don't have to put that many workarounds for current limitations. With GATs and type alias impl trait it would look like this (which we use extensively):

In trait declaration:
```
type IdIterator<'a>: Iterator<...>;
fn ids(&self) -> Self::IdIterator;
```

in concrete trait impl:
```
type IdIterator<'a> = impl Iterator<...> + 'a;
fn ids(&self) -> Self::IdIterator<'_> {
    // something that produces `impl Iterator`
    ...
}
```

With "standard" stable Rust, this is not expresable, especially the part with the lifetime not. For that, you'd have to move the lifetime to the trait itself and use the method indicated in the article. And, instead of `impl Iterator`, you'd need to type in exact type (which is possible, but `impl Trait` makes stuff easier when using iterator transformations).

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/405)* status: all files reviewed, 1 unresolved discussion

___
*[`openraft/src/membership/membership.rs` line 366 at r1](https://reviewable.io/reviews/datafuselabs/openraft/405#-N5U9_YkE0zq4hHGUhbo:-N5ZGA1844XVkzMhsS47:bdtcva3) ([raw file](https://github.com/datafuselabs/openraft/blob/39c17e87d965b8b3ea0b267e5b11c1304f52d586/openraft/src/membership/membership.rs#L366)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

I did not put in the whole example, the `Self::IdIterator` was meant as an exercise to the reader :-). I.e., it's well-known that returning `impl Trait` is not allowed in trait methods, so I assumed, you'd automatically understand it as an associated type.

Well, I'm probably doing too much "hacky" Rust :-). We actually enabled some of the close-to-finalization features to ease development, so we don't have to put that many workarounds for current limitations. With GATs and type alias impl trait it would look like this (which we use extensively):

In trait declaration:
```
type IdIterator<'a>: Iterator<...>;
fn ids(&self) -> Self::IdIterator;
```

in concrete trait impl:
```
type IdIterator<'a> = impl Iterator<...> + 'a;
fn ids(&self) -> Self::IdIterator<'_> {
    // something that produces `impl Iterator`
    ...
}
```

With "standard" stable Rust, this is not expresable, especially the part with the lifetime not. For that, you'd have to move the lifetime to the trait itself and use the method indicated in the article. And, instead of `impl Iterator`, you'd need to type in exact type (which is possible, but `impl Trait` makes stuff easier when using iterator transformations).
</blockquote></details>

I see.
It explains it very well!

Thanks! <3

**Pull request merged**
