### PR TITLE
Refactor: expose AsyncRuntime Oneshot via trait

### LINKED ISSUE #1198: Uniform `AsyncRuntime` channel interfaces
Trait `AsyncRuntime` exposes various associated channel types:

* Oneshot
* MPSC
* Watch

Currently, both MPSC and Watch are exposed through traits:

https://github.com/datafuselabs/openraft/blob/ec284cb4813019d8b3a43a8cd74f3e1aa39eb882/openraft/src/type_config/async_runtime/mod.rs#L120-L122

Oneshot is different, it is scattered in the trait:

```rs
pub trait AsyncRuntime: Debug + Default + PartialEq + Eq + OptionalSend + OptionalSync + 'static {
    // Other fields are omitted

    type OneshotSender<T: OptionalSend>: OneshotSender<T> + OptionalSend + OptionalSync + Sized;
    type OneshotReceiverError: std::error::Error + OptionalSend;
    type OneshotReceiver<T: OptionalSend>: OptionalSend
        + OptionalSync
        + Future<Output = Result<T, Self::OneshotReceiverError>>
        + Unpin;
    fn oneshot<T>() -> (Self::OneshotSender<T>, Self::OneshotReceiver<T>)
    where T: OptionalSend;
}
```

To provide a consistent interface, I kinda think we should expose Oneshot in the way used by MPSC and Watch, i.e., something like:

```rs
pub trait Oneshot {
    type Sender<T: OptionalSend>: OneshotSender<T>;
    type Receiver<T: OptionalSend>: OptionalSend
        + OptionalSync
        + Future<Output = Result<T, Self::ReceiverError>>
        + Unpin;
    type ReceiverError: std::error::Error + OptionalSend;

    fn channel<T>() -> (Self::Sender<T>, Self::Receiver<T>)
    where T: OptionalSend;
}

pub trait AsyncRuntime: Debug + Default + PartialEq + Eq + OptionalSend + OptionalSync + 'static {
    // Other fields are omitted

    type MpscUnbounded: MpscUnbounded; 
    type Watch: Watch; 
    type Oneshot: Oneshot;
}
```

### PR DESCRIPTION
**Pull request by SteveLauC**
### What does this PR do

Exposes `Oneshot` via `trait Oneshot`.

Closes #1198 

**Checklist**

- [ ] Updated guide with pertinent info (may not always apply). 
- [x] Squash down commits to one or two logical commits which clearly describe the work you've done.
- [ ] Unittest is a friend:)

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1200)

### CODE REVIEW

**Comment by SteveLauC** [comment]
Do I need to include a changelog entry in the PR description? Something like

# Changelog
Change: Interfaces of the oneshot channel in `AsyncRunime` have their own trait `trait Oneshot` now

**Comment by drmingdrmer** [comment]
> Do I need to include a changelog entry in the PR description? Something like
> 
> # Changelog
> Change: Interfaces of the oneshot channel in `AsyncRunime` have their own trait `trait Oneshot` now

Use a commit message starts with`Change: `, instead of a `Refactor: ` for a breaking change. It will be included in the change log when publishing. No need to add another `# Changelog` entry in the commit message.

The PR title is not used when building change log.

**Review by drmingdrmer — APPROVED** [review]
Nice shot. Thank you!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1200#-:-O2cSNpU-0M3HBAlymgC:b-oowni6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SteveLauC)

**Comment by SteveLauC** [comment]
> Use a commit message starts withChange: , instead of a Refactor:  for a breaking change.

**Comment by drmingdrmer** [comment]
> > Use a commit message starts withChange: , instead of a Refactor:  for a breaking change.
> 
> This is a breaking change for users who implement their own `AsyncRuntime`, do you need to manually edit the changelog when crafting a new release?

The change log is built with this script:
https://github.com/datafuselabs/openraft/blob/main/scripts/build_change_log.py

After that,  the generated change-log still needs a  few manually update.

**Comment by SteveLauC** [comment]
> The change log is built with this script:
> https://github.com/datafuselabs/openraft/blob/main/scripts/build_change_log.py
>
> After that, the generated change-log still needs a few manually update.

Get it, thanks for showing me this!

**Comment by drmingdrmer** [comment]
> > Use a commit message starts withChange: , instead of a Refactor:  for a breaking change.
> 
> This is a breaking change for users who implement their own `AsyncRuntime`, do you need to manually edit the changelog when crafting a new release?

I forgot the commit message needs to be updated when merging. I've force-pushed the main branch to correct the commit message...

**Comment by SteveLauC** [comment]
> I forgot the commit message needs to be updated when merging. I've force-pushed the main branch to correct the commit message...

Thanks for fixing that for me! 😄

**Pull request merged**
