### PR TITLE
WIP: AsRef

### PR DESCRIPTION
**Pull request by drmingdrmer**
##### WIP: AsRef

---
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/407)

### CODE REVIEW

**Comment by drmingdrmer** [comment]
It looks like using `AsRef<[ID]>` won't work.

I guess it's because the compiler does not whether `BTreeSet` implements `AsRef<[ID]>` too.

```
  --> openraft/src/quorum/quorum_set_impl.rs:29:1
   |
6  | / impl<ID> QuorumSet<ID> for BTreeSet<ID>
7  | | where ID: PartialOrd + Ord + Copy + 'static
8  | | {
9  | |     fn is_quorum<'a, I: Iterator<Item = &'a ID> + Clone>(&self, ids: I) -> bool {
...  |
25 | |     }
26 | | }
   | |_- first implementation here
...
29 | / impl<ID, T> QuorumSet<ID> for T
30 | | where
31 | |     ID: PartialOrd + Ord + Copy + 'static,
32 | |     T: AsRef<[ID]>,
...  |
50 | |     }
51 | | }
   | |_^ conflicting implementation for `std::collections::BTreeSet<_>
```

**Comment by drmingdrmer** [comment]
@schreter

**Review by schreter — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/407)* status: all files reviewed, 1 unresolved discussion (waiting on @ariesdevil, @drmingdrmer, and @lichuang)

___
*[`openraft/src/quorum/quorum_set_impl.rs` line 29 at r1](https://reviewable.io/reviews/datafuselabs/openraft/407#-N5V-_yy0xnhnpdgeu2L:-N5V-IT-8rRbn-LX0f4M:b-qodb5n) ([raw file](https://github.com/datafuselabs/openraft/blob/1c1f26c2b43c6e5ce41586655c5068d57f01bbeb/openraft/src/quorum/quorum_set_impl.rs#L29)):*
> ```XML
> 
> /// Impl a simple majority quorum set
> impl<ID, T> QuorumSet<ID> for T
> ```

No, that won't work (at least not without min_specialization feature).

But I didn't mean it here, I meant it as the third parameter of `impl QuorumSet for Joint`, where you currently use either `Vec` or `&[]` and both implementations are exactly the same. So this third parameter could be then an abstract `AsRef` instead of two different implementations, which are otherwise exactly the same.

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/407)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ariesdevil, @lichuang, and @schreter)

___
*[`openraft/src/quorum/quorum_set_impl.rs` line 29 at r1](https://reviewable.io/reviews/datafuselabs/openraft/407#-N5V-_yy0xnhnpdgeu2L:-N5ZVsTSEA-UHOMicGiz:b-4o3co1) ([raw file](https://github.com/datafuselabs/openraft/blob/1c1f26c2b43c6e5ce41586655c5068d57f01bbeb/openraft/src/quorum/quorum_set_impl.rs#L29)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

No, that won't work (at least not without min_specialization feature).

But I didn't mean it here, I meant it as the third parameter of `impl QuorumSet for Joint`, where you currently use either `Vec` or `&[]` and both implementations are exactly the same. So this third parameter could be then an abstract `AsRef` instead of two different implementations, which are otherwise exactly the same.
</blockquote></details>

I am not sure I understand you correctly.

Using a `D: AsRef<[QS]>` as the third type parameter for `Joint`, it is able to unifies the implementation for `Vec` and `&[]`, but there are still **conflicting implementation error**, when trying to implement `QuorumSet` for another type `Joint<..., BTreeSet<ID>>`:

```rust
/// Implement QuorumSet for Joint<..&[QS]>
impl<'d, ID, QS, D> QuorumSet<ID> for Joint<ID, QS, D>
where
    ID: PartialOrd + Ord + 'static,
    QS: QuorumSet<ID>,
    D: AsRef<[QS]>,
{
    fn is_quorum<'a, I: Iterator<Item = &'a ID> + Clone>(&self, ids: I) -> bool { todo!() }
    fn ids(&self) -> BTreeSet<ID> { todo!() }
}

/// Implement QuorumSet for Joint<..&[QS]>
impl<'d, ID, QS> QuorumSet<ID> for Joint<ID, QS, BTreeSet<ID>>
where
    ID: PartialOrd + Ord + 'static,
    QS: QuorumSet<ID>,
{
    fn is_quorum<'a, I: Iterator<Item = &'a ID> + Clone>(&self, ids: I) -> bool { todo!() }
    fn ids(&self) -> BTreeSet<ID> { todo!() }
}
```

```test
error[E0119]: conflicting implementations of trait `quorum::quorum_set::QuorumSet<_>` for type `quorum::joint::Joint<_, _, std::collections::BTreeSet<_>>`
  --> openraft/src/quorum/joint.rs:59:1
   |
43 | / impl<'d, ID, QS, D> QuorumSet<ID> for Joint<ID, QS, D>
44 | | where
45 | |     ID: PartialOrd + Ord + 'static,
46 | |     QS: QuorumSet<ID>,
...  |
55 | |     }
56 | | }
   | |_- first implementation here
...
59 | / impl<'d, ID, QS> QuorumSet<ID> for Joint<ID, QS, BTreeSet<ID>>
60 | | where
61 | |     ID: PartialOrd + Ord + 'static,
62 | |     QS: QuorumSet<ID>,
...  |
70 | |     }
71 | | }
   | |_^ conflicting implementation for `quorum::joint::Joint<_, _, std::collections::BTreeSet<_>>`
   |
   = note: upstream crates may add a new impl of trait `std::convert::AsRef<[_]>` for type `std::collections::BTreeSet<_>` in future versions
```

**Review by schreter — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/407)* status: all files reviewed, 1 unresolved discussion (waiting on @ariesdevil, @drmingdrmer, and @lichuang)

___
*[`openraft/src/quorum/quorum_set_impl.rs` line 29 at r1](https://reviewable.io/reviews/datafuselabs/openraft/407#-N5V-_yy0xnhnpdgeu2L:-N5ZqPbtC6EOUtdWiHIA:b-cozfqq) ([raw file](https://github.com/datafuselabs/openraft/blob/1c1f26c2b43c6e5ce41586655c5068d57f01bbeb/openraft/src/quorum/quorum_set_impl.rs#L29)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

I am not sure I understand you correctly.

Using a `D: AsRef<[QS]>` as the third type parameter for `Joint`, it is able to unifies the implementation for `Vec` and `&[]`, but there are still **conflicting implementation error**, when trying to implement `QuorumSet` for another type `Joint<..., BTreeSet<ID>>`:

```rust
/// Implement QuorumSet for Joint<..&[QS]>
impl<'d, ID, QS, D> QuorumSet<ID> for Joint<ID, QS, D>
where
    ID: PartialOrd + Ord + 'static,
    QS: QuorumSet<ID>,
    D: AsRef<[QS]>,
{
    fn is_quorum<'a, I: Iterator<Item = &'a ID> + Clone>(&self, ids: I) -> bool { todo!() }
    fn ids(&self) -> BTreeSet<ID> { todo!() }
}

/// Implement QuorumSet for Joint<..&[QS]>
impl<'d, ID, QS> QuorumSet<ID> for Joint<ID, QS, BTreeSet<ID>>
where
    ID: PartialOrd + Ord + 'static,
    QS: QuorumSet<ID>,
{
    fn is_quorum<'a, I: Iterator<Item = &'a ID> + Clone>(&self, ids: I) -> bool { todo!() }
    fn ids(&self) -> BTreeSet<ID> { todo!() }
}
```

```test
error[E0119]: conflicting implementations of trait `quorum::quorum_set::QuorumSet<_>` for type `quorum::joint::Joint<_, _, std::collections::BTreeSet<_>>`
  --> openraft/src/quorum/joint.rs:59:1
   |
43 | / impl<'d, ID, QS, D> QuorumSet<ID> for Joint<ID, QS, D>
44 | | where
45 | |     ID: PartialOrd + Ord + 'static,
46 | |     QS: QuorumSet<ID>,
...  |
55 | |     }
56 | | }
   | |_- first implementation here
...
59 | / impl<'d, ID, QS> QuorumSet<ID> for Joint<ID, QS, BTreeSet<ID>>
60 | | where
61 | |     ID: PartialOrd + Ord + 'static,
62 | |     QS: QuorumSet<ID>,
...  |
70 | |     }
71 | | }
   | |_^ conflicting implementation for `quorum::joint::Joint<_, _, std::collections::BTreeSet<_>>`
   |
   = note: upstream crates may add a new impl of trait `std::convert::AsRef<[_]>` for type `std::collections::BTreeSet<_>` in future versions
```

</blockquote></details>

Well, then it's probably the same problem you had with `QuorumSet` proper and we'll have to wait for min_specialization to land :-(. Just keep it as-is for now, it's not so important (though it would help remove code duplication).

OTOH, why implement it for `BTreeSet<ID>` at all? The last parameter of the `Joint` is the storage of `QuorumSet`s, so how this can be implemented for `BTreeSet<ID>`? That is a single `QuorumSet`.

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/407)* status: all files reviewed, 1 unresolved discussion (waiting on @ariesdevil, @lichuang, and @schreter)

___
*[`openraft/src/quorum/quorum_set_impl.rs` line 29 at r1](https://reviewable.io/reviews/datafuselabs/openraft/407#-N5V-_yy0xnhnpdgeu2L:-N5_OyBD66Gws2YtzlGe:b-78cke4) ([raw file](https://github.com/datafuselabs/openraft/blob/1c1f26c2b43c6e5ce41586655c5068d57f01bbeb/openraft/src/quorum/quorum_set_impl.rs#L29)):*
> we'll have to wait for min_specialization to land

Hmm... fair enough...Let me close this PR.

> why implement it for BTreeSet<ID> at all? 

Because current the membership is stored in a `BTreeSet` and I am not quite sure if a btreeset-based `QuorumSet` will be used during migration to `Progress`.:(

**Pull request closed without merging**
