### PR TITLE
Change: use NodeId instead of RaftTypeConfig if a type only needs node-id as type param.

### PR DESCRIPTION
**Pull request by drmingdrmer**
##### Change: use NodeId instead of RaftTypeConfig if a type only needs node-id as type param.
- Change: from `DefensiveError<C: RaftTypeConfig>` to `DefensiveError<NID: NodeId>`
- Change: from `ErrorSubject<C: RaftTypeConfig>` to `ErrorSubject<NID: NodeId>`
- Change: from `Membership<C: RaftTypeConfig>` to `Membership<NID: NodeId>`
- Change: from `MissingNodeInfo<C: RaftTypeConfig>` to `MissingNodeInfo<NID: NodeId>`
- Change: from `SnapshotMeta<C: RaftTypeConfig>` to `SnapshotMeta<NID: NodeId>`
- Change: from `StorageError<C: RaftTypeConfig>` to `StorageError<NID: NodeId>`
- Change: from `StorageIOError<C: RaftTypeConfig>` to `StorageIOError<NID: NodeId>`
- Change: from `Violation<C: RaftTypeConfig>` to `Violation<NID: NodeId>`
- Change: from `Vote<C: RaftTypeConfig>` to `Vote<NID: NodeId>`
- CI: lint example-raft-kv

---

---
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/261)

### CODE REVIEW

**Review by schreter — COMMENTED** [review]
Yes, that looks better, thanks. However, not sure about DefensiveCheckBase.

BTW, I still can't approve, neither in Reviewabe, nor directly in GitHub PR.

> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/261#-:-MzifXvY0bDI05Ej9H9P:b-2411tq)* status: all files reviewed, 1 unresolved discussion (waiting on @ariesdevil, @drmingdrmer, and @lichuang)

___
*[openraft/src/defensive.rs, line 22 at r1](https://reviewable.io/reviews/datafuselabs/openraft/261#-Mziec4l15yq1VDLB52x:-Mziec4m867k1zNGoI8J:b7q7601) ([raw file](https://github.com/datafuselabs/openraft/blob/d6c8bee074f12254e77a5302002991ba1b6081a4/openraft/src/defensive.rs#L22)):*
> ```XML
> /// Defines methods of defensive checks for RaftStorage independent of the storage type.
> // TODO This can be extended by other methods, as needed. Currently only moved the one for LogReader
> pub trait DefensiveCheckBase<NID: NodeId> {
> ```

I'm not sure this will suffice. If async operations with test runtime will be necessary, then the type config will have to be re-introduced. I.e., for "larger" components I'd keep the type config.

**Review by lichuang — APPROVED** [review]

**Review by drmingdrmer — COMMENTED** [review]
Hmm. Agree with you about `DefensiveCheckBase` :DDD.

I've put you into the role of `Maintain`. You should then be able to do anything you'd like to :thinking: 

> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/261#-:-MzjOakU4FRCp2YfSW0T:b-6bl52j)* status: 21 of 24 files reviewed, 1 unresolved discussion (waiting on @ariesdevil, @drmingdrmer, and @schreter)

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/261)* status: 21 of 24 files reviewed, 1 unresolved discussion (waiting on @ariesdevil and @schreter)

___
*[openraft/src/defensive.rs, line 22 at r1](https://reviewable.io/reviews/datafuselabs/openraft/261#-Mziec4l15yq1VDLB52x:-MznAVKE9Jh-FuUt2cHz:b-29i0o5) ([raw file](https://github.com/datafuselabs/openraft/blob/d6c8bee074f12254e77a5302002991ba1b6081a4/openraft/src/defensive.rs#L22)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

I'm not sure this will suffice. If async operations with test runtime will be necessary, then the type config will have to be re-introduced. I.e., for "larger" components I'd keep the type config.
</blockquote></details>

Defensive checks only need to know the type `NodeId`. It does not really care about the other types in `RaftTypeConfig`: `D: AppData` and `R: AppDataResponse`.
To me, the only reason `DefensiveCheck` needs a `C: RaftTypeConfig` is that it depends on `RaftStorage<C>`.

Does a testing runtime affect any of the types `C::NodeId`, `C::D`, and `C::R`?

**Review by schreter — APPROVED** [review]
> I've put you into the role of Maintain. You should then be able to do anything you'd like to 🤔

Well, don't worry, I don't plan to break things :-). But, indeed, now I'm also offered "approve" button. So I'm approving this one.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/261#-:-MzoVcwACNvRMtu-GjCz:b2cb31s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ariesdevil)

___
*[openraft/src/defensive.rs, line 22 at r1](https://reviewable.io/reviews/datafuselabs/openraft/261#-Mziec4l15yq1VDLB52x:-MzoV7Pv66eSHQV-WKFZ:bjz3br7) ([raw file](https://github.com/datafuselabs/openraft/blob/d6c8bee074f12254e77a5302002991ba1b6081a4/openraft/src/defensive.rs#L22)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Defensive checks only need to know the type `NodeId`. It does not really care about the other types in `RaftTypeConfig`: `D: AppData` and `R: AppDataResponse`.
To me, the only reason `DefensiveCheck` needs a `C: RaftTypeConfig` is that it depends on `RaftStorage<C>`.

Does a testing runtime affect any of the types `C::NodeId`, `C::D`, and `C::R`?
</blockquote></details>

No, these types will be as-is. The testing runtime will provide wrappers for various synchronization primitives, tasking, etc., which will be zero-overhead wrappers for Tokio lib for "real" runtime and a test implementation for deterministic tests. But the runtime itself will be in `RaftTypeConfig`.

**Comment by drmingdrmer** [comment]
> But the runtime itself will be in `RaftTypeConfig`.

Interesting!

**Comment by schreter** [comment]
> > But the runtime itself will be in `RaftTypeConfig`.
>
> Interesting!

The other option would be to pass the `Runtime` as another type parameter, which we likely don't want to have. So, the association on `RaftTypeConfig` seems to me as the best idea.

The next thing is, of course, where we'll get the instance of the runtime, but that should be trivial to solve (make `TokioRuntime` have a `Default` which is used to construct an (empty) instance, create `TestRuntime` explicitly and pass it in a secondary `new_with_runtime()` constructor).

**Pull request merged**
