### PR TITLE
Feature: define custom Entry type for raft log

### PR DESCRIPTION
**Pull request by drmingdrmer**
##### Feature: define custom Entry type for raft log

This commit introduces a new feature that allows applications to define
a custom type for Raft log entries in `RaftTypeConfig`. By setting `Entry =
MyEntry`, where `MyEntry` implements the `RaftEntry` trait, an application
can now define its own log entry type that reflects its architecture.
However, the default implementation, the `Entry` type is still available.

This change provides more flexibility for applications to tailor the
Raft log entry to their specific needs.

- Fix: #705

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/720)

### CODE REVIEW

**Review by schreter — DISMISSED** [review]
> Reviewed 43 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ariesdevil and @lichuang)

___
*[`examples/raft-kv-memstore/src/lib.rs` line 32 at r1](https://reviewable.io/reviews/datafuselabs/openraft/720#-NQfHnS-8rp7oNiyVXHQ:-NQfHnS-8rp7oNiyVXHR:b-vgm7sn) ([raw file](https://github.com/datafuselabs/openraft/blob/e7116ca9a5938613651c97460419388d793ae2ec/examples/raft-kv-memstore/src/lib.rs#L32)):*
> ```XML
> openraft::declare_raft_types!(
>     /// Declare the type configuration for example K/V store.
>     pub ExampleTypeConfig: D = ExampleRequest, R = ExampleResponse, NodeId = ExampleNodeId, Node = BasicNode, Entry = openraft::Entry<ExampleTypeConfig>
> ```

Heh, I think we should dive a bit into macro magic to make some automatic defaults :-)

When I have time, I'll try to look at it (I'm planning on introducing `AsyncRuntime` to wrap tokio runtime ultimately, since that's currently the sole reason why we are still vendoring the crate instead of using the one from github).
___
*[`openraft/src/display_ext.rs` line 24 at r1](https://reviewable.io/reviews/datafuselabs/openraft/720#-NQfIUC04JH6O6jJw0f9:-NQfIUC04JH6O6jJw0fA:b-9e24i) ([raw file](https://github.com/datafuselabs/openraft/blob/e7116ca9a5938613651c97460419388d793ae2ec/openraft/src/display_ext.rs#L24)):*
> ```XML
> /// Implement `Display` for `&[T]` if T is `Display`.
> ///
> /// It outputs at most 5 elements, excluding those from the 5th to the second-to-last one:
> ```

BTW, you could make the "5" a generic `const MAX_ELEMENTS: usize = 5` argument to allow the user to specify.

**Review by schreter — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ariesdevil and @lichuang)

___
*[`openraft/src/display_ext.rs` line 30 at r3](https://reviewable.io/reviews/datafuselabs/openraft/720#-NQpkrOM8h89AmxOZeWy:-NQpkrOM8h89AmxOZeWz:bkpp9hb) ([raw file](https://github.com/datafuselabs/openraft/blob/2c0026ed292a80f07ecc01e6a20cacf65e45fa70/openraft/src/display_ext.rs#L30)):*
> ```XML
> impl<'a, T: fmt::Display> fmt::Display for DisplaySlice<'a, T> {
>     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> std::fmt::Result {
>         const MAX: usize = 5;
> ```

Actually, what I meant was something like this (see below) and adding MAX to the `DisplaySlice` also as a generic const argument with the default value 5, so by default it would print 5 elements, but if you'd specify it explicitly, like `DisplaySlice::<_, 10>(value)`, then it would print 10 values instead.

But, this is actually independent of the change you intended to make.

Such `DisplayOption` and configurable `DisplaySlice` would be helpful in the stdlib...



_Suggestion:_
```XML
impl<'a, T: fmt::Display, const MAX: usize> fmt::Display for DisplaySlice<'a, T, MAX> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> std::fmt::Result {
```

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ariesdevil and @lichuang)

___
*[`openraft/src/display_ext.rs` line 30 at r3](https://reviewable.io/reviews/datafuselabs/openraft/720#-NQpkrOM8h89AmxOZeWy:-NQrJw165bnlXMdvQmMa:b-54i0tw) ([raw file](https://github.com/datafuselabs/openraft/blob/2c0026ed292a80f07ecc01e6a20cacf65e45fa70/openraft/src/display_ext.rs#L30)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Actually, what I meant was something like this (see below) and adding MAX to the `DisplaySlice` also as a generic const argument with the default value 5, so by default it would print 5 elements, but if you'd specify it explicitly, like `DisplaySlice::<_, 10>(value)`, then it would print 10 values instead.

But, this is actually independent of the change you intended to make.

Such `DisplayOption` and configurable `DisplaySlice` would be helpful in the stdlib...
</blockquote></details>

It looks better now. Thank you!

**Comment by drmingdrmer** [comment]
> > Reviewed 3 of 3 files at r2, 18 of 18 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/720)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ariesdevil and @lichuang)
> 
> _[`openraft/src/display_ext.rs` line 30 at r3](https://reviewable.io/reviews/datafuselabs/openraft/720#-NQpkrOM8h89AmxOZeWy:-NQpkrOM8h89AmxOZeWz:bkpp9hb) ([raw file](https://github.com/datafuselabs/openraft/blob/2c0026ed292a80f07ecc01e6a20cacf65e45fa70/openraft/src/display_ext.rs#L30)):_
> 
> > ```
> > impl<'a, T: fmt::Display> fmt::Display for DisplaySlice<'a, T> {
> >     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> std::fmt::Result {
> >         const MAX: usize = 5;
> > ```
> 

@schreter 
It works fine but there is a little tiny problem with this approach: It has to be written in such a way: (

```rust
tracing::debug!(entries = display(DisplaySlice::<_>(entries.as_slice())), "...");
tracing::debug!(entries = display(DisplaySlice(entries.as_slice())), "..."); // Compilation error:  can not infer the value type...
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a3ffaaa54b9d1bdb5a034bc6871e5eba

**Review by schreter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/720)* status: 44 of 50 files reviewed, all discussions resolved (waiting on @ariesdevil and @lichuang)

___
*[`openraft/src/display_ext.rs` line 30 at r3](https://reviewable.io/reviews/datafuselabs/openraft/720#-NQpkrOM8h89AmxOZeWy:-NQu8qWu3wT2jULCuble:bmtt6i7) ([raw file](https://github.com/datafuselabs/openraft/blob/2c0026ed292a80f07ecc01e6a20cacf65e45fa70/openraft/src/display_ext.rs#L30)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

@schreter 
It works fine but there is a little tiny problem with this approach: It has to be written in such a way: (

```rust
tracing::debug!(entries = display(DisplaySlice::<_>(entries.as_slice())), "...");
tracing::debug!(entries = display(DisplaySlice(entries.as_slice())), "..."); // Compilation error:  can not infer the value type...
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a3ffaaa54b9d1bdb5a034bc6871e5eba

</blockquote></details>

Hm, this seems to be a Rust limitation (https://github.com/rust-lang/rust/issues/95486). So you can either remove the MAX or live with `::<_>` :-(.

Alternatively, you can create a wrapper, like here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=eb9630fc5a3ec226f36ae2490b1768d0

With that, you can use either the default or explicit size.

**Pull request merged**
