### PR TITLE
Refactor: add QuorumSet to impl a set of quorum

### PR DESCRIPTION
**Pull request by drmingdrmer**
##### Refactor: add QuorumSet to impl a set of quorum

Move the quorum related functions from `Membership` to standalone mod
`QuorumSet`.

- Auto implement a simple majority quorum set for `BTreeSet` and `slice`.

- Auto implement a joint quorum set for `Vec` of some `QuorumSet`
  implementation.

- Fix: #395

---
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/397)

### CODE REVIEW

**Comment by drmingdrmer** [comment]
@schreter 
Ask the expert:D
Will there be any performance issues with this implementation, in your opinion?

**Review by schreter — COMMENTED** [review]
> Will there be any performance issues with this implementation, in your opinion?

See comments :-).

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/397#-:-N5Jln1yBwHx28X57u0F:bodd5n6)* status: all files reviewed, 1 unresolved discussion (waiting on @ariesdevil, @drmingdrmer, and @lichuang)

___
*[`openraft/src/quorum/quorum_set_impl.rs` line 7 at r1](https://reviewable.io/reviews/datafuselabs/openraft/397#-N5JjR_J92d3tM-lnPsT:-N5JjR_J92d3tM-lnPsU:bh8kpoq) ([raw file](https://github.com/datafuselabs/openraft/blob/b58c62295cb9a42541dd312d368d39b92f3ac0d9/openraft/src/quorum/quorum_set_impl.rs#L7)):*
> ```XML
> 
> /// Impl a simple majority quorum set
> impl<ID> QuorumSet<ID> for BTreeSet<ID>
> ```

BTW, BTreeSet is not particularly suitable for node sets. It is always a rather small set of a few elements, so you are taking a sledgehammer to crack a nut. The BTreeSet implementation does a binary search in the sole root node of the small BTree, which is about order of magnitude slower than a simple linear search. I.e., for small sets typically used in Raft (3-7 participants) a simple array will fit into 1-2 cache lines and with a simple linear search you can do a much more efficient matching.

I.e., it will likely make sense sooner or later to replace BTreeSet in node sets with a dedicated structure, which will perform significantly better for small sets of up to say 7 nodes (and only fall back to BTreeSet for larger ones).



_Code quote:_
```XML
BTreeSet
```
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 12 at r1](https://reviewable.io/reviews/datafuselabs/openraft/397#-N5JiLy--f-WfHZIj07N:-N5JiLy--f-WfHZIj07O:bw1x1rp) ([raw file](https://github.com/datafuselabs/openraft/blob/b58c62295cb9a42541dd312d368d39b92f3ac0d9/openraft/src/quorum/quorum_set_impl.rs#L12)):*
> ```XML
>     fn is_quorum<'a, I: Iterator<Item = &'a ID> + Clone>(&self, ids: I) -> bool {
>         let mut count = 0;
>         let majority = majority_of(self.len());
> ```

BTW, this would also work (but it is a microoptimization). Same below.



_Suggestion:_
```XML
        let limit = self.len();
        for id in ids {
            if self.contains(id) {
                count += 2;
                if count > limit {
                    return true;
                }
            }
        }
```
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 33 at r1](https://reviewable.io/reviews/datafuselabs/openraft/397#-N5Jj57m-5A2vg7QAC1A:-N5Jj57m-5A2vg7QAC1B:bqglwo4) ([raw file](https://github.com/datafuselabs/openraft/blob/b58c62295cb9a42541dd312d368d39b92f3ac0d9/openraft/src/quorum/quorum_set_impl.rs#L33)):*
> ```XML
>         let majority = majority_of(self.len());
> 
>         // TODO(xp): benchmark these two implementations
> ```

Both implementations will yield approximately the same performance, but the one with explicit loop will be slightly faster due to the early exit. Regarding majority checking, same as above.

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/397)* status: all files reviewed, 2 unresolved discussions (waiting on @ariesdevil, @drmingdrmer, and @lichuang)

___
*[`openraft/src/quorum/quorum_set_impl.rs` line 12 at r1](https://reviewable.io/reviews/datafuselabs/openraft/397#-N5JiLy--f-WfHZIj07N:-N5JogT_2vTLOufgKhOg:b-27x0u7) ([raw file](https://github.com/datafuselabs/openraft/blob/b58c62295cb9a42541dd312d368d39b92f3ac0d9/openraft/src/quorum/quorum_set_impl.rs#L12)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

BTW, this would also work (but it is a microoptimization). Same below.
</blockquote></details>

Interesting~ XD
___
*[`openraft/src/quorum/quorum_set_impl.rs` line 33 at r1](https://reviewable.io/reviews/datafuselabs/openraft/397#-N5Jj57m-5A2vg7QAC1A:-N5JovwkEm66RLl3Wfgm:b-kfq7w8) ([raw file](https://github.com/datafuselabs/openraft/blob/b58c62295cb9a42541dd312d368d39b92f3ac0d9/openraft/src/quorum/quorum_set_impl.rs#L33)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Both implementations will yield approximately the same performance, but the one with explicit loop will be slightly faster due to the early exit. Regarding majority checking, same as above.
</blockquote></details>

Right:D a benchmark shows a very similar result. Thanks, man!

**Review by schreter — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/397)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ariesdevil and @lichuang)

**Pull request merged**
