### PR TITLE
Change: Refactor storage APIs

### PR DESCRIPTION
**Pull request by schreter**
This is a larger refactoring of storage APIs to allow more clear ownership of data.

RaftStorage is now refactored to:
- RaftLogReader to read data from the log in parallel tasks independent of the main Raft loop
- RaftStorage to modify the log and the state machine (implements also RaftLogReader) intended to be used in the main Raft loop
- RaftSnapshotBuilder to build the snapshot in background independent of the main Raft loop

The RaftStorage API offers to create new RaftLogReader or RaftSnapshotBuilder on it.

RaftNetwork is also refactored to:
- RaftNetwork responsible for sending RPCs
- RaftNetworkFactory responsible for creating instances of RaftNetwork for sending data to a particular node

All these traits now take &mut self, so it's possible to heavily optimize a lot of stuff by removing any synchronization/lookups and in general to streamline the implementation of the "real" store and network.

All traits are built in such a way that they can be implemented for Arc<T> (or similar) to basically model the original behaviour with &self receiver.

DefensiveCheck was also split to DefensiveCheckBase and DefensiveCheck to allow creating separate checkers for checked LogReader. There is a single TODO in LogReaderExt for one missing check.

Tests run.

Further optimizations of the API to yet better streamline applying log entries to the state machine (if the state machine is complex and can process requests in the background) are still pending.

Further optimizations of the LogReader API to "invert" the semantics to send the functor to process the log entry to the log instead of materializing the log on heap are also pending.

async_trait optimization is pending

Configuration of types to use for optimizing various synchronization operations (like one-shot channel) is pending.

---
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/199)

### CODE REVIEW

**Comment by schreter** [comment]
@drmingdrmer I don't have the rights to add reviewers in this repo. Also my other PRs are sitting there somewhat orphaned... What is the proper process?

BTW, to ease the reviewing in general, especially since I assume there will be rebases, I suggest you attach Reviewable.io to your repository (it is a great tool to improve review process, especially to track open discussions across PR updates, including rebases). Just head to https://reviewable.io, then click on "Reviews" and attach any review to it (or the entire repository - you won't regret it :-)).

**Comment by schreter** [comment]
Ah, example-raft-kv is not modified yet, so tests in the CI fail.

**Comment by drmingdrmer** [comment]
> @drmingdrmer I don't have the rights to add reviewers in this repo. Also my other PRs are sitting there somewhat orphaned... What is the proper process?

Sorry for that. I was working on something else thus it is delayed.
Normally a team member will assign PR to somebody to review, and we just comment with `@somebody` to get somebody's attention:D

**Comment by drmingdrmer** [comment]
> BTW, to ease the reviewing in general, especially since I assume there will be rebases, I suggest you attach Reviewable.io to your repository (it is a great tool to improve review process, especially to track open discussions across PR updates, including rebases). Just head to https://reviewable.io, then click on "Reviews" and attach any review to it (or the entire repository - you won't regret it :-)).

:DDD Looks great!

**Review by schreter — COMMENTED** [review]
> Sorry for that. I was working on something else thus it is delayed.

No problem, I was just wondering.

BTW, for the reviewers: To start reviewing, just start with `network.rs` and `storage.rs`. The rest are adaptations to it, no need to initially review those hundreds lines of code :-).

> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/199#-:-MwYLXhcEktmGf9uNZoX:bobbpsm)* status: 0 of 60 files reviewed, all discussions resolved (waiting on @ariesdevil, @drmingdrmer, and @lichuang)

**Review by schreter — COMMENTED** [review]
> Ah, example-raft-kv is not modified yet, so tests in the CI fail.

I've pushed a second commit fixing the example-raft-kv, hopefully now it'll compile&test well.

> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/199#-:-Mw_fvoN2ripTlZal89W:b-6i48na)* status: 0 of 63 files reviewed, all discussions resolved (waiting on @ariesdevil, @drmingdrmer, and @lichuang)

**Comment by qiuyi116** [comment]
Sorry for the approve operation.
I think I can't do this but found it just success, don't know is there no limit set by this repo or a github bug.

**Comment by drmingdrmer** [comment]
> Sorry for the approve operation. I think I can't do this but found it just success, don't know is there no limit set by this repo or a github bug.

Hmm... it seems everybody can approve... trying to figure out why :(

**Comment by drmingdrmer** [comment]
> Sorry for the approve operation. I think I can't do this but found it just success, don't know is there no limit set by this repo or a github bug.

You can just approve but it does not seem to affect anything.

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 16 of 60 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/199)* status: 17 of 63 files reviewed, 3 unresolved discussions (waiting on @ariesdevil, @lichuang, and @schreter)

___
*[openraft/src/storage.rs, line 159 at r2](https://reviewable.io/reviews/datafuselabs/openraft/199#-MwbTaRL385k_6Et1epe:-MwbTaRL385k_6Et1epf:b4c9lyr) ([raw file](https://github.com/datafuselabs/openraft/blob/b9c516f8b61c02b2386a956eb16938253c3a57d6/openraft/src/storage.rs#L159)):*
> ```XML
>     // This interface is geared toward small file-based snapshots. However, not all snapshots can
>     // be easily represented as a file. Probably a more generic interface will be needed to address
>     // also other needs.
> ```

:thumbsup: 



_Code quote:_
```XML
    // NOTES:
    // This interface is geared toward small file-based snapshots. However, not all snapshots can
    // be easily represented as a file. Probably a more generic interface will be needed to address
    // also other needs.
```
___
*[openraft/src/storage.rs, line 307 at r2](https://reviewable.io/reviews/datafuselabs/openraft/199#-MwbUyZKAI3ks3WIoNxq:-MwbUyZKAI3ks3WIoNxr:b4c9lyr) ([raw file](https://github.com/datafuselabs/openraft/blob/b9c516f8b61c02b2386a956eb16938253c3a57d6/openraft/src/storage.rs#L307)):*
> ```XML
>     /// Returns the last applied log id which is recorded in state machine, and the last applied membership log id and
>     /// membership config.
>     // NOTE: This can be made into sync, provided all state machines will use atomic read or the like.
> ```

:thumbsup: 
___
*[openraft/src/storage.rs, line 328 at r2](https://reviewable.io/reviews/datafuselabs/openraft/199#-MwbVZao2icBxxdb92P5:-MwbVZao2icBxxdb92P6:b4c9lyr) ([raw file](https://github.com/datafuselabs/openraft/blob/b9c516f8b61c02b2386a956eb16938253c3a57d6/openraft/src/storage.rs#L328)):*
> ```XML
>     // then collect completions on this channel and update the client with the result once all
>     // the preceding operations have been applied to the state machine. This way we'll reach
>     // operation pipelining w/o the need to wait for the completion of each operation inline.
> ```

:thumbsup: 



_Code quote:_
```XML
    // TODO The reply should happen asynchronously, somehow. Make this method synchronous and
    // instead of using the result, pass a channel where to post the completion. The Raft core can
    // then collect completions on this channel and update the client with the result once all
    // the preceding operations have been applied to the state machine. This way we'll reach
    // operation pipelining w/o the need to wait for the completion of each operation inline.
```

**Comment by drmingdrmer** [comment]
Has to go to bed now. Not finished reading all of your great work yet.
I'm gonna have to work on something else tomorrow. Hope to be able to finish this PR on Friday:)

**Review by schreter — COMMENTED** [review]
> Has to go to bed now.

Hehe, it's after midnight in your timezone, as I see it :-)

> Hope to be able to finish this PR on Friday:)

Sure, no problem.

BTW, is there some guide how to properly format the TODOs? Also, it would be probably good to create issues for them, to be addressed later. In our project, we are now working on integrating a lot of pieces together, so it's a bit of a moving target yet, therefore I didn't want to refactor it fully.

> Hmm... it seems everybody can approve... trying to figure out why :(

Do you mean approving via Reviewable or approving on GitHub level? I definitely can't approve anything, neither in Reviewable nor in GitHub. The approval in Reviewable is normally transferred to GitHub (and follows GitHub permissions, since it just calls GitHub API).

> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/199#-:-MwbX1ks5UfhjuoMNvvj:biv7hoj)* status: 17 of 63 files reviewed, 3 unresolved discussions (waiting on @ariesdevil, @lichuang, and @schreter)

**Review by lichuang — APPROVED** [review]
sorry for review so late,cause this pr has so many changes,and make me some time to comprehend.

LGTM.

**Comment by drmingdrmer** [comment]
> BTW, is there some guide how to properly format the TODOs? 

If you mean the `TODO` in the code comment, personally I've been used to make it in form of `TODO(<who>): blabla`. 
There isn't a formal style guide for it :)

> Also, it would be probably good to create issues for them, to be addressed later.

Let's do it:D

**Comment by drmingdrmer** [comment]
> Do you mean approving via Reviewable or approving on GitHub level? I definitely can't approve anything, neither in Reviewable nor in GitHub. The approval in Reviewable is normally transferred to GitHub (and follows GitHub permissions, since it just calls GitHub API).

Via github.

I do not know why 🤔 . Searched github doc but did not find anything explaining this.

I have another account `xp-trumpet` for testing privilege issues and this account can just approve:
https://github.com/datafuselabs/openraft/pull/196
image

**Review by drmingdrmer — COMMENTED** [review]
Thanks for this great work:DDD

The new traits introduced split the duties into smaller mods that are much easier to understand.

And these minimized PRs are very comfortable to read. :DDD

**Pull request merged**
