### PR TITLE
Refactor: use std::sync::Mutex for routing_table and isolated_nodes

### PR DESCRIPTION
**Pull request by tangwz**
RaftRouter does not have to use `tokio::sync::RwLock` for routing_table and isolated_nodes.
`std::sync::Mutex` is good enough.

issue: https://github.com/datafuselabs/openraft/issues/165

**Checklist**
- [ ] Updated guide with pertinent info (may not always apply). 
- [x] Squash down commits to one or two logical commits which clearly describe the work you've done. If you don't, then Dodd will `:)`.

### CODE REVIEW

**Comment by tangwz** [comment]
@drmingdrmer PTAL.

**Review by drmingdrmer — APPROVED** [review]
Nice shot man!

**Review by lichuang — APPROVED** [review]

**Comment by drmingdrmer** [comment]
@tangwz 
`make fmt` will fix your lint issue:D

**Comment by drmingdrmer** [comment]
CI failed.

**Comment by tangwz** [comment]
@drmingdrmer PTAL

**Comment by drmingdrmer** [comment]
Looks good~ Thanks man!

**Pull request merged**
