### PR TITLE
Fix: Use NodeId where NodeId is meant, not u64

### PR DESCRIPTION
**Pull request by schreter**
Note: It would be ideal to wrap NodeId into a newtype to prevent wrong usage in the future, but that's a breaking change.

Further, NodeId should ideally be a generic argument of Raft type, but that's even bigger breaking change.

The fix in `suite.rs` is not perfect, since it's still using a literal (as are all the tests).

This change is in preparation for another PR that introduces a possibility to use `NodeId` as a GUID/128-bit entity (e.g., you could also code IPv6 address there directly).

### CODE REVIEW

**Comment by drmingdrmer** [comment]
@mergify update

**Comment by drmingdrmer** [comment]
To be honest, making `NodeId` a generic type is just what I was planning to do! :DDD

Thanks for this clean patch!

**Review by drmingdrmer — APPROVED** [review]

**Comment by schreter** [comment]
> To be honest, making NodeId a generic type is just what I was planning to do! :DDD

Yeah, but the number of generics then keeps increasing. I was thinking about a different approach: instead of adding generics, reduce them to one, which would provide all necessary types as associated types. Then it's extremely easy to add further required types (one-liner for the user to adapt to the change) and also to set defaults (once the relevant Rust feature is complete; then no effect for the user), so you could even think about providing entire set of runtime features that can be implemented more optimally by the user.

> Thanks for this clean patch!

You are welcome!

**Comment by drmingdrmer** [comment]
> Yeah, but the number of generics then keeps increasing. I was thinking about a different approach: instead of adding generics, reduce them to one, which would provide all necessary types as associated types. Then it's extremely easy to add further required types (one-liner for the user to adapt to the change) and also to set defaults (once the relevant Rust feature is complete; then no effect for the user), so you could even think about providing entire set of runtime features that can be implemented more optimally by the user.

Hey man, to me, one trait with associated types looks like a great idea!

**Pull request merged**
