### PR TITLE
Refactor: use clap to impl config default values

### PR DESCRIPTION
**Pull request by PsiACE**
Signed-off-by: Chojan Shang <psiace@outlook.com>

## Changelog

Refactor: use clap to impl config default values

### CODE REVIEW

**Comment by ariesdevil** [comment]
LGTM

**Comment by drmingdrmer** [comment]
Are there differences between `clap::Parser` and `structopt::StructOpt` ? 🤔

**Comment by ariesdevil** [comment]
> Are there differences between `clap::Parser` and `structopt::StructOpt` ? 🤔

I guess it's for consistency with the databend project.

**Comment by PsiACE** [comment]
ref: https://github.com/clap-rs/clap/issues/1574#issuecomment-575919336

**Comment by drmingdrmer** [comment]
> ref: [clap-rs/clap#1574 (comment)](https://github.com/clap-rs/clap/issues/1574#issuecomment-575919336)

Great, got it.

**Pull request merged**
