### PR TITLE
Refactor: add profile HTTP interface to dump flame graph and script in example

### PR DESCRIPTION
**Pull request by lichuang**
Refactor: add profile HTTP interface to dump flame graph and script in example

after that, user can use `test-cluster-and-dump-flamegraph.sh` to dump flame graph file, which can use to profile `openraft` lib.

---
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/213)

### CODE REVIEW

**Review by schreter — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/213)* status: all files reviewed, 4 unresolved discussions (waiting on @drmingdrmer and @lichuang)

___
*[example-raft-kv/Cargo.toml, line 36 at r1](https://reviewable.io/reviews/datafuselabs/openraft/213#-MwvzkCW0NzFPNEktF_Q:-MwvzkCW0NzFPNEktF_R:b7g6nq8) ([raw file](https://github.com/datafuselabs/openraft/blob/ba56f3d1662a1f81fcf11661a3553fbc2f9950e5/example-raft-kv/Cargo.toml#L36)):*
> ```TOML
> thiserror = "1.0.30"
> inferno = { version = "0.10" }
> pprof = { version = "0.6.2", features = ["flamegraph", "protobuf"] }
> ```

Shouldn't these be an optional feature? Especially protobuf brings many dependencies. Is it really needed? It doesn't like it's being used at all, so you can simply remove it from the list of features.

BTW, I looked at the documentation of pprof crate. It is using semi-standard "backtrace" call. In our project, we are very performance-focused, so we already analyzed various options. Unfortunately, backtrace in std is synchronizing on global lock and libunwind does too, so this can be in general only used for very coarse-grained analysis. We are using native tools (Intel vtune's profiler on Intel CPUs, Apple's Instruments on M1 and perf on Linux where we don't have vtune), where vtune is the best of the pack (by a very large margin). In another project, we have a lock-free C++ implementation of backtrace, which is used also for an integrated profiler to quickly analyze issues. That works, but even with the very well optimized lock-free and signal-safe backtrace implementation and using 1-10ms sample intervals for all threads, the results are not particularly helpful, except there is a clear bottleneck.

So let's see what this will produce :-). Did you already test it on something bigger? If so, can you share what you've seen?



_Code quote:_
```TOML
inferno = { version = "0.10" }
pprof = { version = "0.6.2", features = ["flamegraph", "protobuf"] }
```
___
*[example-raft-kv/Cargo.toml, line 49 at r1](https://reviewable.io/reviews/datafuselabs/openraft/213#-Mww-2bn8SlDa6QBXq1i:-Mww-2bn8SlDa6QBXq1j:bn0dtbm) ([raw file](https://github.com/datafuselabs/openraft/blob/ba56f3d1662a1f81fcf11661a3553fbc2f9950e5/example-raft-kv/Cargo.toml#L49)):*
> ```TOML
> 
> [profile.release]
> debug = true
> ```

Hm, activating debug in release hopefully only turns on debugging symbols, but nothing else.

Also: strange line ending
___
*[example-raft-kv/test-cluster-and-dump-flamegraph.sh, line 118 at r1](https://reviewable.io/reviews/datafuselabs/openraft/213#-Mww0LfqE3Rr9WB7JPjA:-Mww0LfqE3Rr9WB7JPjB:b-1pzjoo) ([raw file](https://github.com/datafuselabs/openraft/blob/ba56f3d1662a1f81fcf11661a3553fbc2f9950e5/example-raft-kv/test-cluster-and-dump-flamegraph.sh#L118)):*
> ```Shell
> sleep 1
> 
> nohup curl 127.0.0.1:21001/profile/dump_flamegraph -H "Content-Type: application/json" -d  '[10,99]' &
> ```

You are starting flamegraph here before doing requests. I don't quite get it when it ends. After sending the requests, servers are killed.
___
*[example-raft-kv/test-cluster-and-dump-flamegraph.sh, line 124 at r1](https://reviewable.io/reviews/datafuselabs/openraft/213#-Mww-UHu7DRgRML3Rbdp:-Mww-UHu7DRgRML3Rbdq:byjg7mw) ([raw file](https://github.com/datafuselabs/openraft/blob/ba56f3d1662a1f81fcf11661a3553fbc2f9950e5/example-raft-kv/test-cluster-and-dump-flamegraph.sh#L124)):*
> ```Shell
>     arg='{"Set":{"key":"'$i'","value":"'$i'"}}'
>     echo $arg
>     rpc 21001/write $arg;
> ```

Will this be fast enough to actually bring the server under load? Likely not. But, for starters, might be anyway interesting to see what happens.

Strange line ending in the last line (after "done").



_Code quote:_
```Shell
for i in `seq 1500`
do
    arg='{"Set":{"key":"'$i'","value":"'$i'"}}'
    echo $arg
    rpc 21001/write $arg;
done
```

**Comment by lichuang** [comment]
@schreter This weekend i spent some time on how to generate flame graph on Rust, so i can profile `openraft` in this way.This PR  just add a demo in example, after all, merge into the main may not be appropriate.

@schreter I wonder what tools or methods you used when profiling `openraft`, can u share some idea with us? In the past,  i just dump flame graph and find out the hot pots.

**Comment by schreter** [comment]
> I wonder what tools or methods you used when profiling openraft or other Rust project , can u share some idea with us? I am a C/C++ programer before join openraft project, in the past, i just dump flame graph and find out the hot pots.

@lichuang As already mentioned, we use primarily Intel vtune profiler (which is commercial software and not particularly cheap, unfortunately) at work. This provides the most detailed insights (and IIRC you *can* also generate a flame graph there). Basically, it collects the profiling information by using the hardware counters similar to Linux perf. Then, it allows you to filter the data by time, thread, library, whatever and sort the call graph based on various criteria as you wish (bottom-up, top-down, caller/callee, ...). With that, you can fairly quickly pinpoint real issues. It is also able to attach to a running system (not process) to do system-wide profiling for some time, e.g., on a production server. For "quick" checks, we used our built-in profiler (something like pprof on steroids). That is also possible to activate in production servers by simply turning it on/off at any time. It is however limited to dumping a weighted and colored call graph in .dot format. This one is completely user-space and simply sends round-robin interrupts to all threads (as a signal) and collects callstacks using our lock-free callstack collection algorithm. This happens as fast as possible, typically 1-10ms between samples. The time is then attributed to the respective call graph, which is not perfect, but produces surprisingly good results. And of course, there are other profilers like `perf` in Linux (and only in Linux) or Apple's Xcode `Instruments` which do similar things, but are not as feature-rich as Intel's vtune. Since I'm developing on M1 MBP and on Linux as the backend, I'm primarily using `Instruments` locally to quickly see hotspots and `vtune` for anything more complicated. Unfortunately, `Instruments` doesn't integrate well with Rust (e.g., due to name mangling, but also otherwise, the workflow is badly implemented).

**Comment by lichuang** [comment]
@schreter  Thanks very much, very valuable share!

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/213)* status: all files reviewed, 4 unresolved discussions (waiting on @lichuang and @schreter)

___
*[example-raft-kv/Cargo.toml, line 36 at r1](https://reviewable.io/reviews/datafuselabs/openraft/213#-MwvzkCW0NzFPNEktF_Q:-Mx-LOo90A9FESqyrE9U:bpejsmj) ([raw file](https://github.com/datafuselabs/openraft/blob/ba56f3d1662a1f81fcf11661a3553fbc2f9950e5/example-raft-kv/Cargo.toml#L36)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Shouldn't these be an optional feature? Especially protobuf brings many dependencies. Is it really needed? It doesn't like it's being used at all, so you can simply remove it from the list of features.

BTW, I looked at the documentation of pprof crate. It is using semi-standard "backtrace" call. In our project, we are very performance-focused, so we already analyzed various options. Unfortunately, backtrace in std is synchronizing on global lock and libunwind does too, so this can be in general only used for very coarse-grained analysis. We are using native tools (Intel vtune's profiler on Intel CPUs, Apple's Instruments on M1 and perf on Linux where we don't have vtune), where vtune is the best of the pack (by a very large margin). In another project, we have a lock-free C++ implementation of backtrace, which is used also for an integrated profiler to quickly analyze issues. That works, but even with the very well optimized lock-free and signal-safe backtrace implementation and using 1-10ms sample intervals for all threads, the results are not particularly helpful, except there is a clear bottleneck.

So let's see what this will produce :-). Did you already test it on something bigger? If so, can you share what you've seen?
</blockquote></details>

Agree. It would be better to make profiling a feature of crate openraft.

**Pull request closed without merging**
