### PR TITLE
test: extends timeout for case client_writes

### PR DESCRIPTION
**Pull request by drmingdrmer**

### CODE REVIEW

**Review by ariesdevil — APPROVED** [review]
lgtm

**Comment by drmingdrmer** [comment]
@Mergifyio refresh

**Comment by ariesdevil** [comment]
Seems the robot is not responding to you lol.

**Comment by drmingdrmer** [comment]
> Seems the robot is not responding to you lol.

That's what I am doing... publish some rule and find out whether the bot works...

Please leave us alone...

**Pull request merged**
