### PR TITLE
Feature: add `Raft::data_metrics()` and `Raft::server_metrics()`

### LINKED ISSUE #985: Split metrics into data metrics and server metrics
[RaftMetrics][] encapsulates a range of information about the internal states of
a Raft node, including the server state (e.g., Leader, Follower), and
data-related states such as the last log index and the last applied log index.

Applications interested in monitoring these details can subscribe to
[RaftMetrics][] to receive updates when these metrics change, with
`Raft::metrics()`.

However, some metrics, like `last_log_index`, are frequently updated, while
others, such as `current_term` and `state`, change less often.

For applications solely concerned with server state transitions (like switching
from Leader to Follower), being notified of changes to `last_log_index` can
result in unnecessary wake-ups.

To optimize this, it would be beneficial to add two subsets of the metrics:
- Metrics that are not data-related, such as `current_term`, `vote`, and `state`.
- Metrics that are data-related, including `last_log_index` and `last_applied`.

By segregating these metrics, applications can subscribe to the relevant subset
and reduce the overhead of processing frequent updates that are not pertinent to
their needs.

TODO:

- [ ] add `Raft::data_metrics()` to return a `watch::Receiver<RaftDataMetrics>`
    that contains only metrics about log, state machine and snapshot.

- [ ] add `Raft::server_metrics()` to return a
    `watch::Receiver<RaftServerMetrics>` that contains only server related
    metrics, such as `vote`, `leader`, `id`, `running_state`, `membership`

[RaftMetrics]: https://github.com/datafuselabs/openraft/blob/147de251551c1ed364bd60bbe57047393e1d625e/openraft/src/metrics/raft_metrics.rs#L18

### PR DESCRIPTION
**Pull request by YangKian**
close #985

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/990)

### CODE REVIEW

**Comment by YangKian** [comment]
@drmingdrmer Hi~ I'm done, PTAL when you have time

**Review by drmingdrmer — COMMENTED** [review]
Thank you man.

The metrics producing process can be simplified:)

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/990#-:-No5UIu41Rz0IkZIEwQ8:bnva1hg)* status: all files reviewed, 4 unresolved discussions (waiting on @YangKian)

___
*[`openraft/src/metrics/mod.rs` line 42 at r1](https://reviewable.io/reviews/datafuselabs/openraft/990#-No5U6tY3bq1xwRKQzkJ:-No5U6tY3bq1xwRKQzkK:bbd0vyk) ([raw file](https://github.com/datafuselabs/openraft/blob/e14ac0cd7f89c69822a48d1e8170a71a9795b67e/openraft/src/metrics/mod.rs#L42)):*
> ```XML
> pub use metric::Metric;
> pub use raft_metrics::is_data_metrics_changed;
> pub use raft_metrics::is_server_metrics_changed;
> ```

I think these two functions can be removed since the spawned task I mentioned above is no necessary.
___
*[`openraft/src/metrics/raft_metrics.rs` line 174 at r1](https://reviewable.io/reviews/datafuselabs/openraft/990#-No5RrGh0cR4A3Wc9ZHm:-No5RrGh0cR4A3Wc9ZHn:b6f1d0v) ([raw file](https://github.com/datafuselabs/openraft/blob/e14ac0cd7f89c69822a48d1e8170a71a9795b67e/openraft/src/metrics/raft_metrics.rs#L174)):*
> ```XML
> where NID: NodeId
> {
>     pub last_log_index: Option<u64>,
> ```

OpenRaft prefers the use of `LogId` over `log-index` whenever possible.
`RaftMetrics::last_log_index` is kept for backward compatibility.
For this newly added field, use `last_log: Option<LogId>` instead.
___
*[`openraft/src/metrics/raft_metrics.rs` line 238 at r1](https://reviewable.io/reviews/datafuselabs/openraft/990#-No5SaEj-KEFA0oI4iF9:-No5SaEj-KEFA0oI4iFA:b-r85qcp) ([raw file](https://github.com/datafuselabs/openraft/blob/e14ac0cd7f89c69822a48d1e8170a71a9795b67e/openraft/src/metrics/raft_metrics.rs#L238)):*
> ```XML
> {
>     pub id: NID,
>     pub current_term: u64,
> ```

Openraft uses `Vote` instead of `term` when possible. `current_term` is kept in `RaftMetrics` for backward compatibility. In `RaftServerMetrics`, this field can be removed. An application can just use `vote.leader_id.get_term()` instead.
___
*[`openraft/src/raft/mod.rs` line 210 at r1](https://reviewable.io/reviews/datafuselabs/openraft/990#-No5TUqh1FKO_JYRgXI1:-No5TUqh1FKO_JYRgXI2:blnvsng) ([raw file](https://github.com/datafuselabs/openraft/blob/e14ac0cd7f89c69822a48d1e8170a71a9795b67e/openraft/src/raft/mod.rs#L210)):*
> ```XML
>                 }
>             }
>         });
> ```

you do not have to create another task to replicate the metrics to data-metrics and server-metrics.
Just do this in [`report_metrics`](https://github.com/datafuselabs/openraft/blob/4cf21562fd83876cda02984f152b7f64730aa081/openraft/src/core/raft_core.rs#L522), which is the only entry in Openraft to update metrics.

**Review by YangKian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/990)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @drmingdrmer)

___
*[`openraft/src/metrics/mod.rs` line 42 at r1](https://reviewable.io/reviews/datafuselabs/openraft/990#-No5U6tY3bq1xwRKQzkJ:-No6MluRC8ncDbWEUGFP:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/e14ac0cd7f89c69822a48d1e8170a71a9795b67e/openraft/src/metrics/mod.rs#L42)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

I think these two functions can be removed since the spawned task I mentioned above is no necessary.
</blockquote></details>

Done.
___
*[`openraft/src/metrics/raft_metrics.rs` line 174 at r1](https://reviewable.io/reviews/datafuselabs/openraft/990#-No5RrGh0cR4A3Wc9ZHm:-No6Mf0v9__jOXmGRXMl:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/e14ac0cd7f89c69822a48d1e8170a71a9795b67e/openraft/src/metrics/raft_metrics.rs#L174)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

OpenRaft prefers the use of `LogId` over `log-index` whenever possible.
`RaftMetrics::last_log_index` is kept for backward compatibility.
For this newly added field, use `last_log: Option<LogId>` instead.
</blockquote></details>

Done.
___
*[`openraft/src/metrics/raft_metrics.rs` line 238 at r1](https://reviewable.io/reviews/datafuselabs/openraft/990#-No5SaEj-KEFA0oI4iF9:-No6MgdX8Po34teWAqAt:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/e14ac0cd7f89c69822a48d1e8170a71a9795b67e/openraft/src/metrics/raft_metrics.rs#L238)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

Openraft uses `Vote` instead of `term` when possible. `current_term` is kept in `RaftMetrics` for backward compatibility. In `RaftServerMetrics`, this field can be removed. An application can just use `vote.leader_id.get_term()` instead.
</blockquote></details>

Done.
___
*[`openraft/src/raft/mod.rs` line 210 at r1](https://reviewable.io/reviews/datafuselabs/openraft/990#-No5TUqh1FKO_JYRgXI1:-No6MjsLBcxk0FeM1JFK:b-896fix) ([raw file](https://github.com/datafuselabs/openraft/blob/e14ac0cd7f89c69822a48d1e8170a71a9795b67e/openraft/src/raft/mod.rs#L210)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

you do not have to create another task to replicate the metrics to data-metrics and server-metrics.
Just do this in [`report_metrics`](https://github.com/datafuselabs/openraft/blob/4cf21562fd83876cda02984f152b7f64730aa081/openraft/src/core/raft_core.rs#L522), which is the only entry in Openraft to update metrics.
</blockquote></details>

Done.

**Review by drmingdrmer — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/990)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @YangKian)

**Pull request merged**
