### PR TITLE
dep: Reduce deps restriction

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

This PR will reduce the deps restriction so that end users can link to more versions.

**Checklist**
- [x] Updated guide with pertinent info (may not always apply)
- [x] Squash down commits to one or two logical commits which clearly describe the work you've done. If you don't, then Dodd will `:)`.

---
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/248)

### CODE REVIEW

**Comment by drmingdrmer** [comment]
I do not know if it's a good practice. We once had a condition with an unstable minor version:
- https://github.com/datafuselabs/databend/pull/841
- https://github.com/datafuselabs/databend/pull/862

By loosening the minor version constraint, one dependency upgrade may suddently break user applications.

**Comment by Xuanwo** [comment]
Nice consideration.

First:

- `abc = "1.x.y"` means allow building with all `abc >= "1.x.y"`
- `abc = "1.x.y"` means allow building with all `abc >= "1.x"`

So no matter which style we are using (unless we choose to use `~1.x.y`), an unstable dependency upgrade may suddenly break user applications (they should be addressed by upstream).

This PR intends to allow `openraft` built on more **older** versions.

As `tokio v1.7` seems buggy, may It be better to roll back to a more recent version like `v1.8` instead?

**Comment by drmingdrmer** [comment]
> Nice consideration.
> 
> First:
> 
> * `abc = "1.x.y"` means allow building with all `abc` that `>= 1.x.y, < 2.0.0`
> * `abc = "1.x"` means allow building with all `abc` that  `>= 1.x, < 2.0.0`
> 
> So no matter which style we are using (unless we choose to use `~1.x.y`), an unstable dependency upgrade may suddenly break user applications (they should be addressed by upstream).

You are right! Lesson learned!
Then it seems like nothing is getting worse:|


> This PR intends to allow `openraft` built on more **older** versions.

For curiosity, why do you need to build on some **older** version?

> As `tokio v1.7` seems buggy, may It be better to roll back to a more recent version like `v1.8` instead?

Hmm? What do you mean? It is `1.8` before this patch and `1` in this patch.

**Comment by Xuanwo** [comment]
> For curiosity, why do you need to build on some **older** version?

No obvious reason, just because we can... (and makes `Cargo.toml` more clear)

In this way, we don't need to bump the version unless we really need some new features.

> Hmm? What do you mean? It is `1.8` before this patch and `1` in this patch.

If `tokio v1.7` is buggy, I will change `tokio = "1"` to `tokio = "1.8"` to avoid `1.7` been chosen.

**Comment by schreter** [comment]
BTW, we are using https://github.com/renovatebot/renovate to check and update dependencies in our company. It automatically checks and increments dependencies and runs the CI with them (and optionally automatically merges the updates). I'm not responsible for it, so I don't have much knowledge about it, but it might be interesting. But it's more geared towards the "end product" to keep its dependencies fresh than for a library, which might still be used by an older dependant, forcing it to upgrade its dependencies.

Independent of that, I'm also in favor of making the dependencies more flexible.

**Comment by Xuanwo** [comment]
Thanks for the nice idea! @schreter

I think the dependence policy is different for rust's lib and bin:

- lib SHOULD specify the oldest version that it can build
- bin SHOULD specify the newest version that it can use

It's different for `vendored-deps` language packages like in Node.js. And this is also part of the reason why `Cargo.lock` should be kept for the bin but not for lib.

So both `dependabot` and `renovate` are great choices for binaries, but for libs like `openraft`, it's better to keep depends unchanged unless we need new features.

**Comment by drmingdrmer** [comment]
@Xuanwo 

IMHO, a lib should allow an application to upgrade the dependencies of the lib to the greatest compatible version, but also should specify the least working version, such as `abc = "1.x.y"`.

The changes in this patch allow an application to install an older version of dependency that may have some 
 known bugs, such as:
`derive_more = { version="0.99.9" }` to `derive_more = { version="0.99" }`, there are several fixes in:
https://github.com/JelteF/derive_more/blob/master/CHANGELOG.md

**Comment by schreter** [comment]
> So both dependabot and renovate are great choices for binaries, but for libs like openraft, it's better to keep depends unchanged unless we need new features.

Agreed. I just wanted to point it out, but I also wrote that it's unlikely going to help here.

> Independent of that, I'm also in favor of making the dependencies more flexible.

...of course, only in case it doesn't break things :-). It seems that I misunderstood a bit the dependency management. Therefore, I'll abstain from the further discussion.

For my use case, the current dependencies (except serde issue, but that's being worked on) are just fine.

**Comment by Xuanwo** [comment]
@drmingdrmer @schreter Thanks for all the comments. I have a better understanding of rust's dependencies :laughing: 

I agree that current dependencies work fine. Let's close this PR for now.

**Pull request closed without merging**
