### PR TITLE
Refactor: Implement Custom Async Mutex Using Oneshot Channel

### PR DESCRIPTION
**Pull request by drmingdrmer**
##### Refactor: Implement Custom Async Mutex Using Oneshot Channel

This commit introduces a custom implementation of an asynchronous Mutex
using the `AsyncRuntime::Oneshot` functions, tailored specifically for
Openraft's limited use of asynchronous locks. This custom mutex replaces
the previously used Tokio mutex.

- **Refactor of `RaftInner::tx_shutdown`:** The `tx_shutdown` member of
  `RaftInner` has been changed to use a standard (synchronous) Mutex
  instead of an asynchronous one. This change is made because
  `tx_shutdown` does not span across `.await` points, making the
  asynchronous capabilities unnecessary.

- **OneshotSender `Drop` Implementation:** It is now documented that the
  `OneshotSender` should implement the `Drop` trait to ensure that when
  a sender is dropped, the receiver is notified and yields an error.
  This behavior is crucial for maintaining robust error handling in
  asynchronous communication patterns.

##### Refactor: RaftInner::tx_shutdown should be std Mutx

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1208)

### CODE REVIEW

**Comment by drmingdrmer** [comment]
@SteveLauC

**Review by SteveLauC — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1208)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @drmingdrmer and @schreter)

___
*[`openraft/src/sync/mutex.rs` line 22 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2wdXbH6GZzbDlcLbhM:-O2wdXbH6GZzbDlcLbhN:b-ts3j5v) ([raw file](https://github.com/datafuselabs/openraft/blob/3533ae6f29bd9465573a09a06f7fc97567fc6cb0/openraft/src/sync/mutex.rs#L22)):*
> ```XML
>     /// The current lock holder.
>     ///
>     /// When the acquired `MutexGuard` is dropped, it will notify the next waiting task via this
> ```

Noticed that we didn't explicitly send a `()` in the `Drop` implementation (as there is no manual drop impl), instead, we are utilizing that `rx.await` will return an error when the `tx` (guard.holder) is dropped, is this something we can rely on? Or should we document this requirement in the doc of `trait Oneshot` so that users can know that we rely on it and have it implemented 🤔

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1208)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @schreter and @SteveLauC)

___
*[`openraft/src/sync/mutex.rs` line 22 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2wdXbH6GZzbDlcLbhM:-O2wf9EECoNSihLDmvnY:b-x1lyua) ([raw file](https://github.com/datafuselabs/openraft/blob/3533ae6f29bd9465573a09a06f7fc97567fc6cb0/openraft/src/sync/mutex.rs#L22)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

Noticed that we didn't explicitly send a `()` in the `Drop` implementation (as there is no manual drop impl), instead, we are utilizing that `rx.await` will return an error when the `tx` (guard.holder) is dropped, is this something we can rely on? Or should we document this requirement in the doc of `trait Oneshot` so that users can know that we rely on it and have it implemented 🤔
</blockquote></details>

Correct. The functionality relies on the `Drop` implementation to notify the waiting task. However, there is currently insufficient documentation describing the `Drop` behavior for `OneshotSender`.

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1208)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @drmingdrmer and @schreter)

___
*[`openraft/src/sync/mutex.rs` line 22 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2wdXbH6GZzbDlcLbhM:-O2xAW_B1F4BO3QeC3Dd:bbr111u) ([raw file](https://github.com/datafuselabs/openraft/blob/3533ae6f29bd9465573a09a06f7fc97567fc6cb0/openraft/src/sync/mutex.rs#L22)):*
> However, there is currently insufficient documentation describing the `Drop` behavior for `OneshotSender`.

Then we should document this and probably add a test for it:)

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1208)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @schreter and @SteveLauC)

___
*[`openraft/src/sync/mutex.rs` line 22 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2wdXbH6GZzbDlcLbhM:-O2xEfW21bvWr-fa5_KD:b-xa1v5r) ([raw file](https://github.com/datafuselabs/openraft/blob/3533ae6f29bd9465573a09a06f7fc97567fc6cb0/openraft/src/sync/mutex.rs#L22)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

> However, there is currently insufficient documentation describing the `Drop` behavior for `OneshotSender`.

Then we should document this and probably add a test for it:)
</blockquote></details>

Add a TODO:
- #1209

**Review by schreter — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1208)* status: all files reviewed, 4 unresolved discussions (waiting on @drmingdrmer)

___
*[`openraft/src/raft/mod.rs` line 321 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2xLa4_7pG5N-HC8-MU:-O2xLa4_7pG5N-HC8-MV:b-tny9w4) ([raw file](https://github.com/datafuselabs/openraft/blob/9a5574f3f0aa2d22e9b52285da69332735996fa3/openraft/src/raft/mod.rs#L321)):*
> ```XML
>             rx_data_metrics,
>             rx_server_metrics,
>             tx_shutdown: std::sync::Mutex::new(Some(tx_shutdown)),
> ```

This is a good idea.
___
*[`openraft/src/raft/mod.rs` line 322 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2xLbvl1aaZ9Ssu2myF:-O2xLbvl1aaZ9Ssu2myG:bkon2d5) ([raw file](https://github.com/datafuselabs/openraft/blob/9a5574f3f0aa2d22e9b52285da69332735996fa3/openraft/src/raft/mod.rs#L322)):*
> ```XML
>             rx_server_metrics,
>             tx_shutdown: std::sync::Mutex::new(Some(tx_shutdown)),
>             core_state: Mutex::new(CoreState::Running(core_handle)),
> ```

BTW, there is only a single place where this requires async mutex. You can also rewrite it with synchronous one, by adding an additional state `Joining(watch::Receiver<()>)` to await the task completion and first changing the state to `Joining` and then after the task is fully-joined change to `Done`. With this, there is no need for async mutex here.
___
*[`openraft/src/raft/mod.rs` line 324 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2xN-PG4futLTIDf_Co:-O2xN-PG4futLTIDf_Cp:b-eypk7s) ([raw file](https://github.com/datafuselabs/openraft/blob/9a5574f3f0aa2d22e9b52285da69332735996fa3/openraft/src/raft/mod.rs#L324)):*
> ```XML
>             core_state: Mutex::new(CoreState::Running(core_handle)),
> 
>             snapshot: Mutex::new(None),
> ```

This mutex is also a bit strange (and the last async mutex). It seems to be used only at a single place to protect against parallel receive of multiple snapshots? Strange.

@drmingdrmer Is this lock needed at all? It will anyway call `install_full_snapshot` afterwards.
___
*[`openraft/src/sync/mutex.rs` line 17 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2xKP738Ma4rGY_AQP5:-O2xKP738Ma4rGY_AQP6:beumey9) ([raw file](https://github.com/datafuselabs/openraft/blob/9a5574f3f0aa2d22e9b52285da69332735996fa3/openraft/src/sync/mutex.rs#L17)):*
> ```XML
> /// Since oneshot channel is already required by AsyncRuntime implementation,
> /// there is no need for the application to implement Mutex.
> pub(crate) struct Mutex<C, T>
> ```

Well, though it's interesting implementation, it has some serious drawbacks. Especially, it requires memory allocation for each lock operation, which is a no-go for a `Mutex`, not only making it slow, but also introducing unexpected failure potential.

What I meant is to add a *trait* for `Mutex`, which would be default-implemented by `TokioRuntime` with `tokio::sync::Mutex`. Then, an optimized mutex would be used.

**Review by drmingdrmer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1208)* status: all files reviewed, 3 unresolved discussions (waiting on @schreter)

___
*[`openraft/src/raft/mod.rs` line 322 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2xLbvl1aaZ9Ssu2myF:-O2xS40VDfWA9XhevbEM:b-gu6jsa) ([raw file](https://github.com/datafuselabs/openraft/blob/9a5574f3f0aa2d22e9b52285da69332735996fa3/openraft/src/raft/mod.rs#L322)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

BTW, there is only a single place where this requires async mutex. You can also rewrite it with synchronous one, by adding an additional state `Joining(watch::Receiver<()>)` to await the task completion and first changing the state to `Joining` and then after the task is fully-joined change to `Done`. With this, there is no need for async mutex here.
</blockquote></details>

good idea. I'm going to fix this in anoter PR.
___
*[`openraft/src/raft/mod.rs` line 324 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2xN-PG4futLTIDf_Co:-O2xSLm18tArOqwECcKT:b-n18kwi) ([raw file](https://github.com/datafuselabs/openraft/blob/9a5574f3f0aa2d22e9b52285da69332735996fa3/openraft/src/raft/mod.rs#L324)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

This mutex is also a bit strange (and the last async mutex). It seems to be used only at a single place to protect against parallel receive of multiple snapshots? Strange.

@drmingdrmer Is this lock needed at all? It will anyway call `install_full_snapshot` afterwards.
</blockquote></details>

Yes, there might be multiple parallel chunked snapshot requests received.
___
*[`openraft/src/sync/mutex.rs` line 17 at r2](https://reviewable.io/reviews/datafuselabs/openraft/1208#-O2xKP738Ma4rGY_AQP5:-O2xXbnc8I0rUx_n7tej:b-7z6fo7) ([raw file](https://github.com/datafuselabs/openraft/blob/9a5574f3f0aa2d22e9b52285da69332735996fa3/openraft/src/sync/mutex.rs#L17)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Well, though it's interesting implementation, it has some serious drawbacks. Especially, it requires memory allocation for each lock operation, which is a no-go for a `Mutex`, not only making it slow, but also introducing unexpected failure potential.

What I meant is to add a *trait* for `Mutex`, which would be default-implemented by `TokioRuntime` with `tokio::sync::Mutex`. Then, an optimized mutex would be used.
</blockquote></details>

True. I'll revert this PR.

**Comment by SteveLauC** [comment]
> True. I'll revert this PR.

Let me add the `Mutex` primitive to the `AsyncRuntime` trait this afternoon:)

**Pull request closed without merging**
