### PR TITLE
Test: add an AsyncRuntime test suite

### PR DESCRIPTION
**Pull request by SteveLauC**
### What does this PR do

Implements the test suite for `AsyncRuntime` and tests the built-in `TokioRuntime` impl with it.

**Checklist**

- [ ] Updated guide with pertinent info (may not always apply). 
        I think we need to mention this in `getting-started.md` but I am not sure about where to add it.    
- [ ] Squash down commits to one or two logical commits which clearly describe the work you've done.
- [x] Unittest is a friend:)

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219)

### CODE REVIEW

**Comment by SteveLauC** [comment]
Well, I will handle those CI failures, they are easy to deal with, I simply need to correct the import path.

**Review by drmingdrmer — COMMENTED** [review]
Wow. That's a plenty of work!

> Reviewed 38 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219#-:-O3GxI865KKZUKR0Oa7s:by3g3zx)* status: 38 of 40 files reviewed, 1 unresolved discussion (waiting on @schreter and @SteveLauC)

___
*[`openraft/src/testing/mod.rs` line 40 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3Gv25z87MMyX5Yrvvp:-O3Gv25z87MMyX5Yrvvq:b-xmkeh3) ([raw file](https://github.com/datafuselabs/openraft/blob/fdbf0eb22c9db7c58883dca91a2627cc26a5ca7f/openraft/src/testing/mod.rs#L40)):*
> ```XML
>         crate::Membership::new(config, None),
>     )
> }
> ```

These functions are intended for testing purposes only, yet they remain public. They are utilized not only for **log** tests but also for state machine and network tests. Organizing them into a separate directory is feasible, but we should strive to minimize disruption to user applications by maintaining the existing paths to these functions wherever possible.



_Code quote:_
```XML
mod store_builder;
mod suite;

use std::collections::BTreeSet;

pub use store_builder::StoreBuilder;
pub use suite::Suite;

use crate::entry::RaftEntry;
use crate::CommittedLeaderId;
use crate::LogId;
use crate::RaftTypeConfig;

/// Builds a log id, for testing purposes.
pub fn log_id<NID: crate::NodeId>(term: u64, node_id: NID, index: u64) -> LogId<NID> {
    LogId::<NID> {
        leader_id: CommittedLeaderId::new(term, node_id),
        index,
    }
}

/// Create a blank log entry for test.
pub fn blank_ent<C: RaftTypeConfig>(term: u64, node_id: C::NodeId, index: u64) -> crate::Entry<C> {
    crate::Entry::<C>::new_blank(LogId::new(CommittedLeaderId::new(term, node_id), index))
}

/// Create a membership log entry without learner config for test.
pub fn membership_ent<C: RaftTypeConfig>(
    term: u64,
    node_id: C::NodeId,
    index: u64,
    config: Vec<BTreeSet<C::NodeId>>,
) -> crate::Entry<C> {
    crate::Entry::new_membership(
        LogId::new(CommittedLeaderId::new(term, node_id), index),
        crate::Membership::new(config, None),
    )
}
```

**Comment by SteveLauC** [comment]
> but we should strive to minimize disruption to user applications by maintaining the existing paths to these functions wherever possible.

AH, right, I forgot they're public APIs, will try to maintaining their current import path.

**Comment by SteveLauC** [comment]
> but we should strive to minimize disruption to user applications by maintaining the existing paths to these functions wherever possible.

Ah, right, I forgot they're public APIs, will try to maintaining their current import path.

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219)* status: 3 of 47 files reviewed, 1 unresolved discussion (waiting on @drmingdrmer and @schreter)

___
*[`openraft/src/testing/mod.rs` line 40 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3Gv25z87MMyX5Yrvvp:-O3VPDxa27m6hgNyM7kv:b-cbap2i) ([raw file](https://github.com/datafuselabs/openraft/blob/fdbf0eb22c9db7c58883dca91a2627cc26a5ca7f/openraft/src/testing/mod.rs#L40)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

These functions are intended for testing purposes only, yet they remain public. They are utilized not only for **log** tests but also for state machine and network tests. Organizing them into a separate directory is feasible, but we should strive to minimize disruption to user applications by maintaining the existing paths to these functions wherever possible.
</blockquote></details>

I moved them to a new file `common.rs` and re-exported them in `log/mod.rs` so that  their import paths remain the same:)

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219)* status: 3 of 47 files reviewed, 2 unresolved discussions (waiting on @drmingdrmer and @schreter)

___
*[`openraft/src/testing/runtime/mod.rs` line 36 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3VUjkv7ImRLTBG6ow3:-O3VUjkv7ImRLTBG6ow4:ba6ycgw) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L36)):*
> ```XML
> 
> impl<Rt: AsyncRuntime> Suite<Rt> {
>     pub async fn test_all() {
> ```

I purposely make this an async function so that we don't need to create users' runtime and `block_on()` the tests on the Openraft side, and this is currently impossible as there is no such `block_on()` function in the `AsyncRuntime` trait.

```rs
struct MyCustomRuntime;
impl openraft::AsyncRuntime for MyCustomRuntime { /* omitted */ }

// Build a runtime
let rt = MyCustomRuntime::new();
// Run all the tests
rt.block_on(Suite::<MyCustomRuntime>::test_all());
```

BTW, currently, our log test suite [hardcodes the runtime to Tokio](https://github.com/datafuselabs/openraft/blob/662d888327cb4b25d2da195e6069b44f35c43a62/openraft/src/testing/suite.rs#L1297-L1305), I think we need to make it runtime-agnostic as well

**Review by drmingdrmer — DISMISSED** [review]
> Reviewed 1 of 40 files at r1, 7 of 7 files at r2, 43 of 43 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219)* status: all files reviewed, 1 unresolved discussion (waiting on @schreter and @SteveLauC)

___
*[`openraft/src/testing/mod.rs` line 40 at r1](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3Gv25z87MMyX5Yrvvp:-O3VYsqNCikAir-DVPc-:b-87j11d) ([raw file](https://github.com/datafuselabs/openraft/blob/fdbf0eb22c9db7c58883dca91a2627cc26a5ca7f/openraft/src/testing/mod.rs#L40)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

I moved them to a new file `common.rs` and re-exported them in `log/mod.rs` so that  their import paths remain the same:)
</blockquote></details>

Good!
___
*[`openraft/src/testing/runtime/mod.rs` line 36 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3VUjkv7ImRLTBG6ow3:-O3VZ8IVExfivFHagsDL:bu7i25p) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L36)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

I purposely make this an async function so that we don't need to create users' runtime and `block_on()` the tests on the Openraft side, and this is currently impossible as there is no such `block_on()` function in the `AsyncRuntime` trait.

```rs
struct MyCustomRuntime;
impl openraft::AsyncRuntime for MyCustomRuntime { /* omitted */ }

// Build a runtime
let rt = MyCustomRuntime::new();
// Run all the tests
rt.block_on(Suite::<MyCustomRuntime>::test_all());
```

BTW, currently, our log test suite [hardcodes the runtime to Tokio](https://github.com/datafuselabs/openraft/blob/662d888327cb4b25d2da195e6069b44f35c43a62/openraft/src/testing/suite.rs#L1297-L1305), I think we need to make it runtime-agnostic as well
</blockquote></details>

Make sense.

**Comment by SteveLauC** [comment]
@schreter, hi, would like to have your review as well, could you please take a look:)

**Review by schreter — COMMENTED** [review]
> @schreter, hi, would like to have your review as well, could you please take a look:)

I didn't forget you, but I have too much on my plate :-(.

> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219#-:-O3WPr-w0toj2mSgbc7e:bv0mr0c)* status: all files reviewed, 1 unresolved discussion (waiting on @SteveLauC)

**Review by schreter — COMMENTED** [review]
Just a quick review with some comments.

> Reviewed 3 of 40 files at r1, 1 of 7 files at r2, 43 of 43 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219#-:-O3WbzsQ0B6gQiKguTsa:b-5yzdfj)* status: all files reviewed, 7 unresolved discussions (waiting on @SteveLauC)

___
*[`openraft/src/testing/runtime/mod.rs` line 67 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3WZGYi1-v1GH_6tUJj:-O3WZGYi1-v1GH_6tUJk:b99sbwc) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L67)):*
> ```XML
>     pub async fn test_sleep() {
>         let start_time = std::time::Instant::now();
>         let dur_100ms = std::time::Duration::from_millis(100);
> ```

I'd suggest to lower this to 10ms or so

same below (several times)

Also, you can factor this out to a constant to reuse in multiple tests.
___
*[`openraft/src/testing/runtime/mod.rs` line 71 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3WZJ4E3N5Ektc1XZtv:-O3WZJ4E3N5Ektc1XZtw:b-hcx3cy) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L71)):*
> ```XML
>         let elapsed = start_time.elapsed();
> 
>         assert!(elapsed > dur_100ms);
> ```

`>=` to be on the safe side (very unlikely it'll hit)

same below
___
*[`openraft/src/testing/runtime/mod.rs` line 101 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3WZWNDAhqm_tg2xmey:-O3WZWNDAhqm_tg2xmez:bg4msd2) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L101)):*
> ```XML
> 
>         // Will time out
>         let dur_150ms = std::time::Duration::from_millis(150);
> ```

I'd suggest to increase this to a second or more, since you can have a hiccup on the system blocking it for couple hundred ms (even for seconds, but unlikely).

Same below.
___
*[`openraft/src/testing/runtime/mod.rs` line 180 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3W_HtG7DmaZrjERmyM:-O3W_HtG7DmaZrjERmyN:b-sf7c1p) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L180)):*
> ```XML
> 
>         for idx in 0..n_senders {
>             let tx = Arc::clone(&tx);
> ```

Why not simply `tx.clone()`?
___
*[`openraft/src/testing/runtime/mod.rs` line 227 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3W_whl6LyFRC0bejT-:-O3W_whl6LyFRC0bejT0:bfk5a47) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L227)):*
> ```XML
> 
>         tx.send(overwrite).unwrap();
>         rx.changed().await.unwrap();
> ```

It would be good to take this future also before `send()` to verify that it indeed changes state afterwards (in a second test/next step of the test). For that, you can do something like this:

```rust
let fut = rx.changed();
let fut = Pin::new(&mut fut);
assert!(poll_in_place(fut), matches!(Poll::Pending));
tx.send(...);
assert!(poll_in_place(fut), matches!(Poll::Ready(...)));
```

There is some support for such feats in `futures` crate. For example, you can do this:

```rust
pub fn poll_in_place<F: Future>(fut: Pin<&mut F>) -> Poll<F::Output> {
    let waker = futures::task::noop_waker();
    let mut cx = Context::from_waker(&waker);
    fut.poll(&mut cx)
}
```

You can also use it elsewhere to fine-grained check when the future becomes ready, especially for sync primitives.
___
*[`openraft/src/testing/runtime/mod.rs` line 316 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3WbOcm2yT-3lGbiP0v:-O3WbOcm2yT-3lGbiP0w:b-psu1nr) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L316)):*
> ```XML
> 
>             handles.push(handle);
>         }
> ```

This is most likely unreliable for a negative test. You don't know where and when the tasks get spawned. They may as well execute sequentially and you won't see broken mutex.

However, you can create a second (or more) futures from `mutex.lock()` and simply check they are not ready and become ready immediately after releasing the lock using `poll_in_place()` mentioned above.



_Code quote:_
```XML
        for _ in 0..n_task {
            let counter = Arc::clone(&counter);
            let handle = Rt::spawn(async move {
                let mut guard = counter.lock().await;
                *guard += 1;
            });

            handles.push(handle);
        }
```

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219)* status: 46 of 47 files reviewed, 4 unresolved discussions (waiting on @drmingdrmer and @schreter)

___
*[`openraft/src/testing/runtime/mod.rs` line 67 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3WZGYi1-v1GH_6tUJj:-O3WmMFM3g-4rMYc9k6I:bb7f2mf) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L67)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

I'd suggest to lower this to 10ms or so

same below (several times)

Also, you can factor this out to a constant to reuse in multiple tests.
</blockquote></details>

done
___
*[`openraft/src/testing/runtime/mod.rs` line 71 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3WZJ4E3N5Ektc1XZtv:-O3WmNAIDx9eNYwRDK_g:bb7f2mf) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L71)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

`>=` to be on the safe side (very unlikely it'll hit)

same below
</blockquote></details>

done
___
*[`openraft/src/testing/runtime/mod.rs` line 101 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3WZWNDAhqm_tg2xmey:-O3WmOLT02VjX4jLgofo:bb7f2mf) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L101)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

I'd suggest to increase this to a second or more, since you can have a hiccup on the system blocking it for couple hundred ms (even for seconds, but unlikely).

Same below.
</blockquote></details>

done
___
*[`openraft/src/testing/runtime/mod.rs` line 180 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3W_HtG7DmaZrjERmyM:-O3Wmssk3LHat8h_2ZId:b-krj42x) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L180)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

Why not simply `tx.clone()`?
</blockquote></details>

`Arc::clone(&p)` is [generally considered a better style](https://news.ycombinator.com/item?id=34429403) than `p.clone()` when it comes to reference-counted pointers, there is a [lint](https://rust-lang.github.io/rust-clippy/master/#/clone_on_ref_ptr) for it (disabled by default).

Changed to `tx.clone()` as Openraft does not use this style.

**Comment by SteveLauC** [comment]
*[`openraft/src/testing/runtime/mod.rs` line 227 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3W_whl6LyFRC0bejT-:-O3Wtj_m6adTqXPfpjAb:b-ub522e) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L227)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

It would be good to take this future also before `send()` to verify that it indeed changes state afterwards (in a second test/next step of the test). For that, you can do something like this:

```rust
let fut = rx.changed();
let fut = Pin::new(&mut fut);
assert!(poll_in_place(fut), matches!(Poll::Pending));
tx.send(...);
assert!(poll_in_place(fut), matches!(Poll::Ready(...)));
```

There is some support for such feats in `futures` crate. For example, you can do this:

```rust
pub fn poll_in_place<F: Future>(fut: Pin<&mut F>) -> Poll<F::Output> {
    let waker = futures::task::noop_waker();
    let mut cx = Context::from_waker(&waker);
    fut.poll(&mut cx)
}
```

You can also use it elsewhere to fine-grained check when the future becomes ready, especially for sync primitives.
</blockquote></details>

done, see this commit: https://github.com/datafuselabs/openraft/pull/1219/commits/46ffc3ef0112aa37b0fd612bb6922b85ad753c14

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219)* status: 46 of 47 files reviewed, 3 unresolved discussions (waiting on @drmingdrmer and @schreter)

___
*[`openraft/src/testing/runtime/mod.rs` line 316 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3WbOcm2yT-3lGbiP0v:-O3Ww0wN7IymFE-j0eVu:b7ij97f) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L316)):*
I renamed this test to `test_mutex_contention()` and added another test to test the case you described:

> However, you can create a second (or more) futures from `mutex.lock()` and simply check they are not ready and become ready immediately after releasing the lock using `poll_in_place()` mentioned above.

See this commit https://github.com/datafuselabs/openraft/pull/1219/commits/77ad0ab7d60f6ee9624d09527bd62e02d0a4cf42

**Review by schreter — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219)* status: all files reviewed, 1 unresolved discussion (waiting on @drmingdrmer and @SteveLauC)

___
*[`openraft/src/testing/runtime/mod.rs` line 180 at r3](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3W_HtG7DmaZrjERmyM:-O3XDqws21f6sDvl8klf:b2i6dli) ([raw file](https://github.com/datafuselabs/openraft/blob/445fccb882c85ae86038b5961910afa1564d42d8/openraft/src/testing/runtime/mod.rs#L180)):*
<details><summary><i>Previously, SteveLauC (SteveLauC) wrote…</i></summary><blockquote>

`Arc::clone(&p)` is [generally considered a better style](https://news.ycombinator.com/item?id=34429403) than `p.clone()` when it comes to reference-counted pointers, there is a [lint](https://rust-lang.github.io/rust-clippy/master/#/clone_on_ref_ptr) for it (disabled by default).

Changed to `tx.clone()` as Openraft does not use this style.
</blockquote></details>

Interesting opinion, which certainly has some merits.

According to an old discussion [here](https://github.com/rust-lang/rust-clippy/issues/2048), it's not that popular, though...

The standard docs [here](https://doc.rust-lang.org/std/sync/struct.Arc.html#cloning-references) say "`Arc<T>`’s implementations of traits like `Clone` **may also be called using fully qualified syntax**. Some people prefer to use fully qualified syntax, while others prefer using method-call syntax." (highlight mine). Since quite a few examples in `Arc` use fully-qualified syntax, I'd say there is no agreement among library writers here :-).

Anyway, since the whole codebase uses `clone()` method call directly, I'd also go with `clone()` method call here.
___
*[`openraft/src/testing/runtime/mod.rs` line 362 at r6](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3XG6CjASHBu9kuKmbh:-O3XG6CjASHBu9kuKmbi:b-6rdw5c) ([raw file](https://github.com/datafuselabs/openraft/blob/77ad0ab7d60f6ee9624d09527bd62e02d0a4cf42/openraft/src/testing/runtime/mod.rs#L362)):*
> ```XML
> }
> 
> /// A helper function to peek a future's state.
> ```

It actually polls, not peeks :-).

**Review by SteveLauC — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219)* status: 46 of 47 files reviewed, 1 unresolved discussion (waiting on @drmingdrmer and @schreter)

___
*[`openraft/src/testing/runtime/mod.rs` line 362 at r6](https://reviewable.io/reviews/datafuselabs/openraft/1219#-O3XG6CjASHBu9kuKmbh:-O3Xj4dH7nqBaM3ofww9:b-w1ki81) ([raw file](https://github.com/datafuselabs/openraft/blob/77ad0ab7d60f6ee9624d09527bd62e02d0a4cf42/openraft/src/testing/runtime/mod.rs#L362)):*
<details><summary><i>Previously, schreter wrote…</i></summary><blockquote>

It actually polls, not peeks :-).
</blockquote></details>

Right, updated:)

**Review by schreter — DISMISSED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @drmingdrmer)

**Review by drmingdrmer — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/openraft/1219)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SteveLauC)

**Comment by SteveLauC** [comment]
Commits squashed.

**Comment by SteveLauC** [comment]
Let me rebase my branch to handle the conflicts:)

**Pull request merged**
