### PR TITLE
Doc: update example: remove NodeManager; remove API list-node, use metrics instead. Do not need AddNode anymore.

### PR DESCRIPTION
**Pull request by drmingdrmer**
##### Doc: update example: remove NodeManager; remove API list-node, use metrics instead. Do not need AddNode anymore.
The latest openraft is able to store node addresses in `Membership`.
Thus the `exmaple-raft-kv` does not need to store node-id to address
mapping by itself.

##### Change: Raft::add_learner() accepts optional arg `Node`.
When adding a learner, an optional `Node` can be provided to store
additional info of a node in Membership.

A common usage if to store node address in the Membership so that an
application does not need another component to get address of a node
when implementing `RaftNetwork`.

- Add type `Node`.

- Membership: add field `nodes` to store a map from NodeId to Node.

- Feature: Raft::initialize() accepts a `BTreeSet<NodeId>` if the
  application do not want to store additional info(the old way) or
  `BTreeMap<NodeId, Node>`.

---

- fix: #162

### CODE REVIEW

**Review by ariesdevil — APPROVED** [review]
LGTM

**Comment by lichuang** [comment]
LGTM

**Comment by ppamorim** [comment]
@drmingdrmer Question: How much more expensive is to call metrics to get the list of nodes?

**Comment by drmingdrmer** [comment]
> @drmingdrmer Question: How much more expensive is to call metrics to get the list of nodes?

@ppamorim 
The `Metrics` is cached behind a lock.
Retrieving it on the server is just acquiring the lock and copying several hundreds of bytes.
Thus, IMO,  there should not be perceivable performance change.

Is there any problem with getting the node list from the `metrics`?

**Comment by ppamorim** [comment]
I can get the list because it's not a `pub` value. I had to do that:
```rust
let metrics_response = app
  .raft
  .metrics()
  .borrow()
  .clone();
let input = serde_json::to_string(&metrics_response.membership_config.membership).unwrap();
let membership: Membership = serde_json::from_str(&input).unwrap();
membership.nodes.unwrap_or_default()
```

**Comment by drmingdrmer** [comment]
Does this method provide what you want?

https://github.com/datafuselabs/openraft/blob/96d9a960bc6817971607f9d60ac4198ab7810d70/openraft/src/core/mod.rs#L118-L121

**Comment by ppamorim** [comment]
@drmingdrmer Yes thank you!

**Pull request merged**
